Add Licenses Subscription Data for Users
openedx-unsupported/frontend-app-support-tools pull request #102
Opened 2021-04-01 17:15 UTC by azanbinzahid

[PROD-2257](https://openedx.atlassian.net/browse/PROD-2257)

2021-04-08 15:21 UTC, DawoudSheraz requested changes
added a few minor comments to address

2021-04-08 15:21 UTC, DawoudSheraz commented on src/users/UserPage.jsx
> +          />
Add a related condition in UserPage.test.jsx successful page load test(verify that this element is rendered)

2021-04-08 15:21 UTC, DawoudSheraz commented on src/users/data/api.js
> +    defaultResponse.status = 'Successful';
For success, don't show any status at all. This info will be helpful for the failure cases only.

2021-04-08 15:21 UTC, DawoudSheraz commented on src/users/Licenses.jsx
> +            <Badge variant="light">{`Fetch Status: ${responseStatus}`}</Badge>
Show the status if there is an error fetching the results. No need to show success status(redundant given that data request call has return successfully and tableData.length signifies how many data elements have been returned).

2021-04-08 16:15 UTC, azanbinzahid commented on src/users/data/api.js
> +    defaultResponse.status = 'Successful';
Code updated

2021-04-08 16:15 UTC, azanbinzahid commented on src/users/Licenses.jsx
> +            <Badge variant="light">{`Fetch Status: ${responseStatus}`}</Badge>
updated

2021-04-08 16:16 UTC, azanbinzahid commented on src/users/UserPage.jsx
> +          />
Having difficulty in understanding this, can you elaborate?

2021-04-08 16:57 UTC, DawoudSheraz commented on src/users/Licenses.jsx
> +    statusMsg = <></>;
Use React Fragment to create empty element

2021-04-08 16:58 UTC, DawoudSheraz approved these changes
a nit to address before merging.

2021-04-08 17:53 UTC, awaisdar001 commented on src/users/Licenses.jsx
> +  const [sortDirection, setSortDirection] = useState('desc');
This can be a good candidate for a boolean value. 
```
const [sortInAscendingOrder, setSortInAscendingOrder] = useState(False);
```

2021-04-08 17:55 UTC, awaisdar001 commented on src/users/Licenses.jsx
> +      setSortDirection(sortDirection === 'desc' ? 'asc' : 'desc');
this could become 
```
if (sortColumn === column) {
    setSortInAscendingOrder(!sortInAscendingOrder) 
} else {
    setSortDirection(False);
}
```

2021-04-08 17:57 UTC, awaisdar001 commented on src/users/Licenses.jsx
> +    statusMsg = <></>;
I think this is the newer way to create an empty component that is identical to React.Fragment. The only difference is that older versions of the JSX Babel plugin didn’t understand <>, so if you need to support those older versions you need to use <Fragment>, otherwise it makes no difference.

2021-04-08 17:59 UTC, awaisdar001 approved these changes
👍 Nice work -- Just wanted to flag that my comments just for info and are not blockers.

2021-04-09 06:13 UTC, Ali-D-Akbar commented on src/users/Licenses.test.jsx
> +    tableHeaders.forEach(header => {
There is some coverage that is being dropped in Licenses.jsx and It can be covered by checking the labels for each row.

2021-04-09 06:17 UTC, Ali-D-Akbar commented on src/users/data/test/licenses.js
> +      activationDate: '2021-04-01',
I think you should use `Date().toLocaleString()` instead of manually adding a date.

2021-04-09 09:40 UTC, azanbinzahid commented on src/users/Licenses.jsx
> +    statusMsg = <></>;
I think using `null` would also work here.

2021-04-09 09:47 UTC, azanbinzahid commented on src/users/Licenses.jsx
> +      setSortDirection(sortDirection === 'desc' ? 'asc' : 'desc');
Yes, this would simplify the logic here but then we would still need to convert this boolean to `asc` and `desc` later when passing props to `Table` component.

2021-04-09 10:07 UTC, azanbinzahid commented on src/users/data/test/licenses.js
> +      activationDate: '2021-04-01',
The API actually is returning a date with dashes in between, and `Date().toLocaleString()` is returning in some other format.

2021-04-09 12:05 UTC, Ali-D-Akbar commented on src/users/data/test/licenses.js
> +      activationDate: '2021-04-01',
Ohh, I guess you should preferably try some other formatting functions.

2021-04-09 12:05 UTC, azanbinzahid commented on src/users/Licenses.test.jsx
> +    tableHeaders.forEach(header => {
I have tried to get example from other components but unable to find, may be we can address this in separate PR where we will add tests for table in all components.

2021-04-09 12:10 UTC, Ali-D-Akbar commented on src/users/Licenses.test.jsx
> +    tableHeaders.forEach(header => {
I recently added something similar in the tests here: https://github.com/edx/frontend-app-support-tools/blob/0760f3d9cb2e8a54b74d06f00205eaca3e664330/src/users/entitlements/Entitlements.test.jsx#L66

It checks the headings and covers these lines.

2021-04-09 12:16 UTC, azanbinzahid commented on src/users/data/test/licenses.js
> +      activationDate: '2021-04-01',
`new Date().toISOString().replace(/T.*/,'')` this worked

2021-04-09 15:04 UTC, azanbinzahid commented on src/users/Licenses.test.jsx
> +    tableHeaders.forEach(header => {
Just added a test for header length

2021-04-09 15:52 UTC, Ali-D-Akbar approved these changes

2021-04-09 17:08 UTC, merged