refactor: add test coverage to various files
openedx-unsupported/frontend-app-support-tools pull request #113
Opened 2021-05-04 02:44 UTC by Ali-D-Akbar

[PROD-2354](https://openedx.atlassian.net/browse/PROD-2354)
Adding and changing some tests and files to increase test coverage for Support Tools.

2021-05-04 10:41 UTC, DawoudSheraz commented on src/users/enrollments/Enrollments.test.jsx
> +      sortButton.simulate('click');
What is being tested here? What happens when the button is clicked?

2021-05-04 10:42 UTC, DawoudSheraz commented on src/users/entitlements/EntitlementForm.jsx
> +  let form = null;
why is this change done?

2021-05-04 10:42 UTC, DawoudSheraz commented on src/users/entitlements/EntitlementForm.test.jsx
> +  });
Why is this test needed?

2021-05-04 10:43 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.test.jsx
> +    const dataTable = wrapper.find('table.w-100');
use table.table

2021-05-04 10:43 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.test.jsx
> +    });
Again, what is the effect of clicking sort button? Also, why 2 clicks?

2021-05-04 10:43 UTC, DawoudSheraz commented on src/utils/index.test.js
> +    };
use meaningful names as compared to dict1, dict2

2021-05-04 10:44 UTC, DawoudSheraz requested changes
added some questions and comments to address

2021-05-04 10:49 UTC, Ali-D-Akbar commented on src/users/enrollments/Enrollments.test.jsx
> +      sortButton.simulate('click');
In order to check all possible cases for this code in [Enrollment.js](https://github.com/edx/frontend-app-support-tools/blob/master/src/users/enrollments/Enrollments.jsx#L84):

`const setSort = useCallback((column) => {
    if (sortColumn === column) {
      setSortDirection(sortDirection === 'desc' ? 'asc' : 'desc');
    } else {
      setSortDirection('desc');
    }
    setSortColumn(column);
  });`
  
both `simulate` calls must be done in order to call `setSortDirection`

2021-05-04 10:52 UTC, Ali-D-Akbar commented on src/users/entitlements/EntitlementForm.jsx
> +  let form = null;
It's a better practice to write if-else if instead of 3 if conditions it also helps cover a couple more lines.

2021-05-04 10:53 UTC, Ali-D-Akbar commented on src/users/entitlements/EntitlementForm.test.jsx
> +  });
in order to increase test coverage.

2021-05-04 10:54 UTC, Ali-D-Akbar commented on src/users/entitlements/Entitlements.test.jsx
> +    const dataTable = wrapper.find('table.w-100');
it was causing problems as it may get more than 1 table component. Although I'll try this again.

2021-05-04 11:09 UTC, DawoudSheraz commented on src/users/enrollments/Enrollments.test.jsx
> +      sortButton.simulate('click');
Ok, separate out the tests(with asc and desc)

2021-05-04 11:11 UTC, DawoudSheraz commented on src/users/entitlements/EntitlementForm.test.jsx
> +  });
Hmm, if it doesn't give an actual advantage other than the coverage, don't include it.

2021-05-04 11:12 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.test.jsx
> +    const dataTable = wrapper.find('table.w-100');
use [hostNodes](https://enzymejs.github.io/enzyme/docs/api/ShallowWrapper/hostNodes.html)() if there is only 1 table but the result is both Table and table.

2021-05-04 19:37 UTC, Ali-D-Akbar commented on src/users/enrollments/Enrollments.test.jsx
> +      sortButton.simulate('click');
I think it'd be redundant to write another test as I'll be writing two variation of the buttons clicks (with 1 and the other with 2 button clicks)

2021-05-04 19:37 UTC, Ali-D-Akbar commented on src/users/entitlements/EntitlementForm.test.jsx
> +  });
Removed.

2021-05-04 19:38 UTC, Ali-D-Akbar commented on src/utils/index.test.js
> +    };
changed names.

2021-05-05 12:23 UTC, Ali-D-Akbar commented on src/users/entitlements/Entitlements.test.jsx
> +    const dataTable = wrapper.find('table.w-100');
Used another approach here as I was only receiving 2 table (not `Table`) elements.

2021-05-05 12:52 UTC, DawoudSheraz requested changes
some comments to address

2021-05-05 12:52 UTC, DawoudSheraz commented on src/users/enrollments/Enrollments.test.jsx
> +      sortButton.simulate('click');
No, it would not be redundant. Plus, add some checks to validate sorting has taken place. Just clicking does not indicate the success of sort.

2021-05-05 12:52 UTC, DawoudSheraz commented on src/users/entitlements/EntitlementForm.jsx
> +  let form = null;
Hmm, not a very compelling argument just to increase coverage.

2021-05-05 12:52 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.test.jsx
> +      }
you don't add if conditions inside tests unnecessarily. Fetch the exact button via index and test appropriately. As for sort, again, test that sorting has actually worked(html structure changed etc.)

2021-05-06 11:32 UTC, Ali-D-Akbar commented on src/users/entitlements/EntitlementForm.jsx
> +  let form = null;
Removing it.

2021-05-06 11:33 UTC, Ali-D-Akbar commented on src/users/enrollments/Enrollments.test.jsx
> +      sortButton.simulate('click');
I covered both cases in one test and added assertions in it.

2021-05-06 11:33 UTC, Ali-D-Akbar commented on src/users/entitlements/Entitlements.test.jsx
> +      }
removed if condition. My bad.

2021-05-06 13:43 UTC, DawoudSheraz commented on src/users/enrollments/Enrollments.test.jsx
> +      expect(wrapper.find('svg.fa-sort-up')).toHaveLength(1);
nice

2021-05-06 13:44 UTC, DawoudSheraz commented on src/users/licenses/Licenses.jsx
> -          defaultSortedColumn="status"
why remove this?

2021-05-06 13:44 UTC, DawoudSheraz approved these changes

2021-05-06 14:14 UTC, Ali-D-Akbar commented on src/users/licenses/Licenses.jsx
> -          defaultSortedColumn="status"
I thought of removing sort by default just like the other sortColumns to keep the consistency.

2021-05-06 16:29 UTC, azanbinzahid approved these changes
added some questions but they are not blockers.

2021-05-06 16:29 UTC, azanbinzahid commented on src/users/UserPage.test.jsx
> +      expect(document.title).toEqual('Support Tools | edX');
For future reference, we can define some site-wide constants e.g. Site title and we can just reference those anywhere needed.

2021-05-06 16:29 UTC, azanbinzahid commented on src/users/entitlements/CreateEntitlementForm.test.jsx
> +      wrapper.find('input#courseUuid').simulate('change', { target: { value: 'b4f19c72-784d-4110-a3ba-318666a7db1a' } });
where is this value coming from? can we use this value directly from some object instead of manually writing here?

2021-05-06 18:47 UTC, Ali-D-Akbar commented on src/users/entitlements/CreateEntitlementForm.test.jsx
> +      wrapper.find('input#courseUuid').simulate('change', { target: { value: 'b4f19c72-784d-4110-a3ba-318666a7db1a' } });
It is just a dummy course uuid. We don't have any of these stored anywhere ATM.

2021-05-06 18:48 UTC, Ali-D-Akbar commented on src/users/UserPage.test.jsx
> +      expect(document.title).toEqual('Support Tools | edX');
Right. We can discuss this and get this done in the next installment of increasing coverage.

2021-05-06 19:17 UTC, merged