fix: search useremail with +
openedx-unsupported/frontend-app-support-tools pull request #120
Opened 2021-05-24 16:40 UTC by azanbinzahid

### [PROD-2359](https://openedx.atlassian.net/browse/PROD-2359)

### Description
Fix search user page and URL route to search users with email having plus (+) in them.

Then:
![image](https://user-images.githubusercontent.com/47540683/119378870-2d115300-bcd8-11eb-9c73-8fcd2c17ddf4.png)

Now:
![image](https://user-images.githubusercontent.com/47540683/119378799-18cd5600-bcd8-11eb-8d9a-d2c9a9080c55.png)

2021-05-24 17:03 UTC, DawoudSheraz commented on src/users/UserPage.jsx
> +
Why is this needed? What happens if decoding is not done? 
Code comment: The code is difficult to understand. Improve variable naming and maybe add an inline comment to explain this special case.

2021-05-24 17:04 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +  const encodedTestEmail = encodeURIComponent(testEmail);
don't introduce a new variable. Use testEmail directly. Change its value to encoded value though.

2021-05-24 17:06 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +      }
you can use the ternary operator to simplify this if condition.

2021-05-24 17:06 UTC, DawoudSheraz requested changes
Added a few comments to address.

2021-05-24 17:15 UTC, azanbinzahid commented on src/users/UserPage.jsx
> +
Earlier method `new URL()` auto converts plus (+) into space without letting us encode/decode only params part. Parsing params from location.search requires string manipulation and then concatenations which makes code much lengthy.  This map converts params in url to key/value pairs. 

Decoding here allows both kind of urls in search i.e. `/?email=abc+d@gmail.com` and `/?email=abc%2Bd%40gmail.com` otherwise only first one will work.

2021-05-24 17:16 UTC, azanbinzahid commented on src/users/data/api.test.js
> +      }
using ternary operating for this exceeds line char limit forcing to split lines again.

2021-05-24 17:24 UTC, Ali-D-Akbar commented on src/users/data/api.test.js
> +      mockAdapter.onGet(`${userAccountApiBaseUrl}?email=${encodedTestEmail}`).reply(200, successResponse);
Can't we just use the normal value for this? I think it can be written without encoding.

2021-05-24 17:24 UTC, Ali-D-Akbar commented on src/users/data/api.test.js
> +      const encodedTestEmailWithPlus = encodeURIComponent(testEmailWithPlus);
Can be written in a single variable as said before.

2021-05-24 17:33 UTC, azanbinzahid commented on src/users/data/api.test.js
> +      mockAdapter.onGet(`${userAccountApiBaseUrl}?email=${encodedTestEmail}`).reply(200, successResponse);
I tried this, but it fails the test and encoding is needed only when making a get call from mockAdapter. We are now sending encoded email when making a regular api call to server and in this case the expected and real response match.

2021-05-24 18:15 UTC, azanbinzahid commented on src/users/data/api.test.js
> +      }
```
const successResponse = {
  ...Array.isArray(responseType) ? responseType[0] : responseType, testEmail: testEmailWithPlus,
};
```
This could be one way if that's readable?

2021-05-24 18:17 UTC, azanbinzahid commented on src/users/UserPage.jsx
> +
These are few more approaches for getting query params: https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript

2021-05-25 09:51 UTC, DawoudSheraz approved these changes

2021-05-25 11:29 UTC, Ali-D-Akbar approved these changes
👍

2021-05-25 11:30 UTC, merged