[WIP]feat: add view certificate button
openedx-unsupported/frontend-app-support-tools pull request #121
Opened 2021-05-24 18:09 UTC by DawoudSheraz

2021-06-24 18:46 UTC, Ali-D-Akbar requested changes
A handful of queries to be addressed:

1. Can you please add a screenshot for regenerate button scenario? Just wanted to confirm that only one of the button is shown
2. What does a user see as a verification that an operation was successful?

2021-06-24 18:46 UTC, Ali-D-Akbar commented on src/users/data/api.test.js
> +  const regenerateCertificateUrl = `${getConfig().LMS_BASE_URL}/certificates/regenerate`;
Why're you not using getCertificateUrl, regenerateCertificateUrl and regenerateCertificateUrl from urls.js?

2021-06-24 18:46 UTC, Ali-D-Akbar commented on src/users/enrollments/Certificates.test.jsx
> +  };
Move this in src/users/data/test/certificates.js.

2021-06-24 18:46 UTC, Ali-D-Akbar commented on src/users/enrollments/Certificates.test.jsx
> +      expect(generateButton.prop('disabled')).toBeFalsy();
why is the generate-certificate button still not disabled after flow has been successful?
And are we showing some success message on success of certificate generation?

2021-06-24 18:46 UTC, Ali-D-Akbar commented on src/users/enrollments/Certificates.test.jsx
> +      expect(generateButton.prop('disabled')).toBeFalsy();
why is the generate-certificate button still not disabled after flow has been successful?
And are we showing some success message on success of certificate generation?

2021-06-25 09:34 UTC, DawoudSheraz commented on src/users/enrollments/Certificates.test.jsx
> +  };
This is not the exact data. The data is already in cert.js.

2021-06-25 09:37 UTC, DawoudSheraz commented on src/users/enrollments/Certificates.test.jsx
> +      expect(generateButton.prop('disabled')).toBeFalsy();
Because it is still possible to generate/regenerate after one attempt. The backend does not restrict reattempts for generation/regeneration. Ideally, the generate button would change into the regenerate button. But the mock in this current test is returning the generatable certificate data.

2021-06-25 09:37 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +  const regenerateCertificateUrl = `${getConfig().LMS_BASE_URL}/certificates/regenerate`;
Right, I will change it

2021-06-25 09:38 UTC, DawoudSheraz commented
> A handful of queries to be addressed:
> 
> 1. Can you please add a screenshot for regenerate button scenario? Just wanted to confirm that only one of the button is shown
> 2. What does a user see as a verification that an operation was successful? Some sort of a success message or the whole page/component refresh?

1. Ok, although there won't be much difference. Only status text is changed.
2. If the generate/regenerate is successful, only the cert component reloads. This behavior is the same as the old support tools, where the reloading is done via django.

2021-06-25 10:12 UTC, Ali-D-Akbar approved these changes

2021-06-25 10:19 UTC, azanbinzahid commented on src/users/data/api.js
> +    return Array.isArray(data) && data.length > 0 ? data[0] : data;
In what cases this endpoint will return an array or single item?

2021-06-25 10:19 UTC, azanbinzahid commented on src/users/data/api.js
> +    return data;
What does `data` contain in this case? from [here](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/views/support.py#L223) it says its a http response. Are we using it anywhere?

2021-06-25 10:19 UTC, azanbinzahid commented on src/users/data/urls.js
> +}/certificates/search?user=${username}&course_id=${courseKey}`;
we may need to encode `courseKey`.

2021-06-25 10:19 UTC, azanbinzahid commented on src/users/enrollments/Certificates.jsx
> +        <table className="table">
Is there a specific reason for not using `Table` component?

2021-06-25 10:25 UTC, DawoudSheraz commented on src/users/data/api.js
> +    return data;
Yeah, it is just a response. We are not using it anywhere though. The return value is used only in tests to verify the api behavior.

2021-06-25 10:27 UTC, DawoudSheraz commented on src/users/enrollments/Certificates.jsx
> +        <table className="table">
Yes, the Table component is more suited for listing with headings on top and data listed vertically. In cert case, the headers are on the left and data on right i.e. one header and one piece of data are on the same row. furthermore, the Table component has many other operations not needed in this case.

2021-06-25 10:29 UTC, DawoudSheraz commented on src/users/data/api.js
> +    return Array.isArray(data) && data.length > 0 ? data[0] : data;
If course id is mentioned, then the single item, otherwise a list of certificates. We might not need this check. I added it for cautious purposes(unexpected data on stage/prod). Once the changes are live, I will validate and remove the unnecessary check.

2021-06-25 10:36 UTC, DawoudSheraz commented on src/users/data/urls.js
> +}/certificates/search?user=${username}&course_id=${courseKey}`;
Hmm, the backend is running quote_plus on the course key. https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/views/support.py#L109. I will check if the encoding is necessary.
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus

2021-06-28 07:54 UTC, DawoudSheraz commented on src/users/data/urls.js
> +}/certificates/search?user=${username}&course_id=${courseKey}`;
Encoding is not needed. Encoding the courseId results in 404 on backend.

2021-06-28 07:56 UTC, azanbinzahid approved these changes

2021-06-28 09:02 UTC, merged