feat: Add create new enrollment button
openedx-unsupported/frontend-app-support-tools pull request #124
Opened 2021-06-02 20:50 UTC by Ali-D-Akbar

A `create new enrollment` button has been added as shown below:

<img width="1403" alt="Screenshot 2021-06-03 at 1 20 16 AM" src="https://user-images.githubusercontent.com/52413434/120546921-ddcecf00-c409-11eb-9592-e87f365ab09a.png">

This is how the `create new enrollment` form looks like:

<img width="1403" alt="Screenshot 2021-06-03 at 1 28 26 AM" src="https://user-images.githubusercontent.com/52413434/120547783-00adb300-c40b-11eb-82a3-362d4a8f9a89.png">

Clicking the submit button will create a post request against the enrollment API. Clicking cancel will hide the form as expected.

TO-DO:

- [ ]  Add unit tests for the newer react components

- [ ] Determine how we're gonna handle the course enrollment modes for a specific course run id. (We can add all possible modes if we can't get modes for a specific course run id.)

2021-06-14 18:07 UTC, DawoudSheraz requested changes

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/data/api.js
> +            'There was an error submitting this enrollment. Check the JavaScript console for detailed errors.',
Error creating the enrollment, not submitting the enrollment

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +        reason: 'test mode change',
test enrollment creation instead of test mode change

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +          message: 'enrollment mode changed',
you are creating enrollment, not changing enrollment. Please maintain consistency in the text.

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/data/test/createEnrollmentForm.js
> +export default createEnrollmentFormData;
no need to create a separate file. Instead, add it in enrollmentsForm(renamed to enrollments.js).

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +  ];
Since this list is same as the change enrollment form, make it a constant and move it out of this file to constants.js inside enrollment component directory.

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/enrollments/EnrollmentActions.jsx
> +export const CREATE = 'create';
move them to constants.js

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/enrollments/EnrollmentModes.jsx
> +export default modes;
Move them to constants.js too.

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/enrollments/Enrollments.test.jsx
> +  });
you are not looping in the test, so why include the words `individual enrollment`? Unless there are issues with tests, use loop to verify that the form renders correctly(by asserting against some data present in the row)

2021-06-14 18:07 UTC, DawoudSheraz commented on src/users/enrollments/Enrollments.test.jsx
>    });
Are you checking the presence of create new enrollment button separately/default values check test?

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/data/test/changeEnrollmentForm.js
> +const changeEnrollmentFormData = {
keep the file name enrollmentForm.js. Add any enrollment form-related data in this file.

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/data/test/enrollments.js
> +};
Move it to enrollmentForm.js for the sake of consistency. Or remove enrollmentForm.js and move the changeenrollmentform data in enrollments.js

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/enrollments/ChangeEnrollmentForm.test.jsx
> +      expect(wrapper.find('button.btn-primary').getDOMNode()).toHaveProperty('disabled');
why are you getting dom node? You can use prop('disabled') to verify the button disability.

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +  closeHandler,
Why is a change handler needed in create enrollment form?

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +        changeHandler();
Instead of calling the change handler, it would be better to add some success indicator. IF the component mysteriously vanishes after the enrollment creation, it can leave a bad user experience.

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +            )}
there is only one class name. Why are you using classNames then?

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/enrollments/CreateEnrollmentForm.test.jsx
> +      expect(wrapper.find('button.btn-primary').getDOMNode()).toHaveProperty('disabled');
no need to get dom node.

2021-06-15 09:53 UTC, DawoudSheraz commented on src/users/enrollments/constants.js
> +  { label: 'Executive Education', value: 'executive-education' },
strings, followed by dict. Alphabetic sorting. The current organization is hard to read.

2021-06-15 14:45 UTC, Ali-D-Akbar commented on src/users/data/test/enrollments.js
> +};
I guess moving everything to a single file makes the most sense. I'll move into enrollments.js

2021-06-15 16:47 UTC, Ali-D-Akbar commented on src/users/enrollments/ChangeEnrollmentForm.test.jsx
> +      expect(wrapper.find('button.btn-primary').getDOMNode()).toHaveProperty('disabled');
I think this line does nothing in particular other than checking if the button isn't disabled. Removing this.

2021-06-15 17:23 UTC, Ali-D-Akbar commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +            )}
Removing this.

2021-06-15 17:23 UTC, Ali-D-Akbar commented on src/users/enrollments/CreateEnrollmentForm.test.jsx
> +      expect(wrapper.find('button.btn-primary').getDOMNode()).toHaveProperty('disabled');
Removing this.

2021-06-15 17:46 UTC, Ali-D-Akbar commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +        changeHandler();
We're doing the same thing for such actions in all components here. I think we should cater this in another ticket where we can add proper success and failure messages rather than just practically restart the page.

2021-06-16 05:21 UTC, DawoudSheraz commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +        changeHandler();
No, it is workable in this PR. Since we are moving towards optimization and a better user experience, let's start by incorporating them into these new features.

2021-06-16 11:44 UTC, Ali-D-Akbar commented on src/users/enrollments/CreateEnrollmentForm.jsx
> +        changeHandler();
I've added this instead of calling the `changeHandler`. Closing the message still causes an error. (for which, I've made a separate ticket [PROD-2349](https://openedx.atlassian.net/browse/PROD-2349))
<img width="955" alt="Screenshot 2021-06-16 at 4 41 47 PM" src="https://user-images.githubusercontent.com/52413434/122212877-c25fcb80-cec1-11eb-99bd-b022f38a7e88.png">

2021-06-16 15:55 UTC, DawoudSheraz approved these changes
merge the backend change PR first. Once that is on stage, merge this PR(when you get 2nd approval) and verify the changes on stage.

2021-06-17 12:17 UTC, azanbinzahid commented on src/users/enrollments/EnrollmentForm.jsx
> +  }
Nice implementation.

2021-06-17 12:21 UTC, azanbinzahid commented on src/users/enrollments/ChangeEnrollmentForm.jsx
> +        <AlertList topic="enrollments" className="mb-3" />
is it okay to add this into the form?

2021-06-17 12:25 UTC, azanbinzahid commented on src/users/enrollments/Enrollments.jsx
> +      <div className="d-flex flex-row justify-content-between mb-2">
we may move this to css files

2021-06-17 12:26 UTC, azanbinzahid approved these changes

2021-06-17 12:42 UTC, Ali-D-Akbar commented on src/users/enrollments/ChangeEnrollmentForm.jsx
> +        <AlertList topic="enrollments" className="mb-3" />
We're planning to move the alerts outside the form. It'll be done in [PROD-2386](https://openedx.atlassian.net/browse/PROD-2386).

2021-06-18 10:44 UTC, merged