refactor: self-contain license component
openedx-unsupported/frontend-app-support-tools pull request #132
Opened 2021-06-29 12:14 UTC by azanbinzahid

### Description
This PR refactors license component towards self-containment, essentially moving its API calls into its own component. This  change is a part of optimization for support tools [PROD-2363](https://openedx.atlassian.net/browse/PROD-2363). 

### Linked Ticket:
[PROD-2394](https://openedx.atlassian.net/browse/PROD-2394)

2021-06-30 03:29 UTC, DawoudSheraz commented on src/users/licenses/Licenses.jsx
> +
What will be the behavior/render before the API call is successful? Empty table? or loading bar?

2021-06-30 03:30 UTC, DawoudSheraz reviewed
A comment/question to address.

2021-06-30 07:48 UTC, Ali-D-Akbar commented on src/users/licenses/Licenses.test.jsx
> +    apiMock.mockRestore();
We don't need to `mockRestore` if we're using `mockImplementationOnce`.
Also, I'd suggest `wrapper.unmount();` in afterEach so that failing one test doesn't affect the others in any way.

2021-06-30 07:59 UTC, Ali-D-Akbar requested changes
Just a small change in tests. 
I'd also suggest adding a loading bar while the component fetches the data from API.

2021-06-30 09:07 UTC, azanbinzahid commented on src/users/licenses/Licenses.jsx
> +
Empty table since initial state of license is empty list. Didn't implement loading bar since its collapsible but should we?

2021-06-30 09:27 UTC, azanbinzahid commented on src/users/licenses/Licenses.test.jsx
> +    apiMock.mockRestore();
thanks, let me look at it.

2021-07-01 09:58 UTC, azanbinzahid commented on src/users/licenses/Licenses.test.jsx
> +    apiMock.mockRestore();
updated as suggested.

2021-07-01 10:48 UTC, Ali-D-Akbar approved these changes
LGTM.

2021-07-01 10:50 UTC, DawoudSheraz approved these changes
:shipit:

2021-07-01 11:11 UTC, merged