refactor: move api calls in entitlement component
openedx-unsupported/frontend-app-support-tools pull request #133
Opened 2021-06-30 07:02 UTC by Ali-D-Akbar

[PROD-2395](https://openedx.atlassian.net/browse/PROD-2395)
Entitlement api calls have been moved from UserPage.jsx to Entitlements.jsx hence the component no longer depends on UserPage.jsx.

I've also added a Page Loading while the entitlement is fetching data from api. Also the tests have been thoroughly changed according to the entitlement changes.

2021-06-30 10:54 UTC, DawoudSheraz commented on src/users/data/api.js
> +  if (data.next && data.next !== null) {
why is there a change in the condition needed?

2021-06-30 10:54 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.jsx
> +      setEntitlementData(camelCaseResult);
what if there is an error during the fetch? How will that be dealt with?

2021-06-30 11:04 UTC, Ali-D-Akbar commented on src/users/data/api.js
> +  if (data.next && data.next !== null) {
Oh, this is unnecessary. Removing it.

2021-06-30 12:08 UTC, azanbinzahid requested changes
Some changes to address ^

2021-06-30 12:08 UTC, azanbinzahid commented on src/users/UserPage.jsx
>              changeHandler={handleEntitlementsChange}
Why can't we move this handler into its own component?

2021-06-30 12:08 UTC, azanbinzahid commented on src/users/entitlements/Entitlements.jsx
> +      {!entitlementData && <PageLoading srMessage="Loading" />}
this can be improved, like adding information of what is being loaded. Ideally the loader should be inside table body so that it does not distort UI before/after loading.

2021-06-30 12:08 UTC, azanbinzahid commented on src/users/entitlements/Entitlements.jsx
> +      {entitlementData && (
it can be a proper if condition combining above line like if there is data then table (or table body) otherwise loader.

2021-06-30 12:08 UTC, azanbinzahid commented on src/users/entitlements/Entitlements.test.jsx
> +  const entitlementWrapperData = {
can be renamed to props (optional)

2021-06-30 14:09 UTC, Ali-D-Akbar commented on src/users/UserPage.jsx
>              changeHandler={handleEntitlementsChange}
The change in Entitlement is subjected to the states of UserPage.jsx as it uses these handlers to expand/hide some collapsible components. In this case, the handler will expand entitlement collapsible and hide the rest.

2021-06-30 14:13 UTC, Ali-D-Akbar commented on src/users/entitlements/Entitlements.jsx
> +      {!entitlementData && <PageLoading srMessage="Loading" />}
I'd still go for a loading bar below "Create New Enrollment" eventually serves the same role as a frequent user will understand that there will be a list of entitlements once it has been loaded.

2021-06-30 14:29 UTC, Ali-D-Akbar commented on src/users/entitlements/Entitlements.test.jsx
> +  const entitlementWrapperData = {
Done.

2021-06-30 14:29 UTC, Ali-D-Akbar commented on src/users/entitlements/Entitlements.jsx
> +      {entitlementData && (
Changed this with a ternary operator.

2021-06-30 16:56 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.jsx
> +      )}
We expect the errors to be displayed via alert list in entitlments as well, even though we are not doing it right now. This ternary operator will make it difficult to adjust the third code segment.

2021-06-30 16:58 UTC, DawoudSheraz commented on src/users/data/api.test.js
> -      mockAdapter.onGet(`${entitlementsApiBaseUrl}&page=1`).reply(200, { results: [], next: null });
why was this removed?

2021-06-30 16:59 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.jsx
> +              disabled={Boolean(!entitlement.enrollmentCourseRun)}
why is Boolean call needed?

2021-07-01 10:18 UTC, DawoudSheraz commented on src/users/entitlements/Entitlements.jsx
> +        setEntitlementData({ results: [] });
@Ali-D-Akbar Please cater for this missed coverage. That is why coverage is dropping.

2021-07-01 12:39 UTC, DawoudSheraz approved these changes

2021-07-01 12:55 UTC, azanbinzahid approved these changes

2021-07-01 13:19 UTC, merged