refactor: self contain user summary and move modals
openedx-unsupported/frontend-app-support-tools pull request #144
Opened 2021-08-30 08:45 UTC by Ali-D-Akbar

[PROD-2393](https://openedx.atlassian.net/browse/PROD-2393)
Moving all the modals out of the user summary to their separate components.

2021-08-31 11:05 UTC, DawoudSheraz requested changes
- Move all the actions in a folder called account-actions inside user
- add tests for each component. The tests are already in UserSummary. They just need to be moved appropriately.

2021-08-31 15:47 UTC, DawoudSheraz approved these changes
Address the nits in tests before merging.

2021-08-31 15:47 UTC, DawoudSheraz commented on src/users/account-actions/PasswordHistory.test.jsx
> +  <UserMessagesProvider>
we would not need message provider here. We are not using any alert component.

2021-08-31 15:47 UTC, DawoudSheraz commented on src/users/account-actions/ResetPassword.test.jsx
> +  <UserMessagesProvider>
same, no need for message provider.

2021-08-31 15:47 UTC, DawoudSheraz commented on src/users/account-actions/TogglePasswordStatus.test.jsx
> +  <UserMessagesProvider>
and here too

2021-08-31 18:18 UTC, Ali-D-Akbar commented on src/users/account-actions/PasswordHistory.test.jsx
> +  <UserMessagesProvider>
Ah, I missed those. Removing them.

2021-09-01 09:19 UTC, azanbinzahid approved these changes
Toggling password status refreshes whole user data, is it expected? If yes then it is good to go.

2021-09-01 09:44 UTC, Ali-D-Akbar commented
> Toggling password status refreshes whole user data, is it expected? If yes then it is good to go.

Yes, it is the expected. We will revisit this probably in the near future.

2021-09-01 09:55 UTC, merged