feat: add sso record compoenents v2
openedx-unsupported/frontend-app-support-tools pull request #145
Opened 2021-09-05 22:42 UTC by azanbinzahid

## Description
This PR adds Card and List component for SSO Records as part of Support Tool Redesign

## Linked Ticket
[PROD-2459](https://openedx.atlassian.net/browse/PROD-2459)
[PROD-2460](https://openedx.atlassian.net/browse/PROD-2460)

## Screenshots
![image](https://user-images.githubusercontent.com/47540683/132143258-0724a36c-061e-4e91-979a-3f1d2e7f1201.png)

## TODO
- get initial review
- write component test
- add instructions to test components locally 
- replace alert (to show value) with modal

2021-09-07 09:30 UTC, DawoudSheraz commented on src/users/v2/SingleSignOnRecordCard.jsx
> +          navigator.clipboard.writeText(value);
does this give a visual indication that copy action has taken place?

2021-09-07 09:30 UTC, DawoudSheraz commented on src/users/v2/SingleSignOnRecordCard.jsx
> +          alert(value); // Modal can be used instead of alert()
let's keep this alert for now.

2021-09-07 09:30 UTC, DawoudSheraz commented on src/users/v2/SingleSignOnRecordCard.jsx
> +              data={[data]}
Why is data conversion to a list of dict necessary?

2021-09-07 09:35 UTC, azanbinzahid commented on src/users/v2/SingleSignOnRecordCard.jsx
> +          navigator.clipboard.writeText(value);
just added

2021-09-07 09:35 UTC, azanbinzahid commented on src/users/v2/SingleSignOnRecordCard.jsx
> +              data={[data]}
Table accepts data as list of dict.

2021-09-08 07:46 UTC, DawoudSheraz commented on src/users/v2/CopyShowHyperLinks.jsx
> +export default function CopyShowHyperlinks({ textValue }) {
nit: either text or value would be good.

2021-09-08 07:47 UTC, DawoudSheraz reviewed
codewise, the changes look good. I will test it out on local as well. You can work on adding tests.

2021-09-08 07:56 UTC, Ali-D-Akbar reviewed
The changes look good to me as well. I just need to verify the UI on local. 👍

2021-09-08 07:56 UTC, Ali-D-Akbar commented on src/users/v2/SingleSignOnRecordsList.jsx
> +export default function SingleSignOnRecords({ username }) {
Just for the consistency, can we name the file `SingleSignOnRecords.jsx` instead?

2021-09-08 17:18 UTC, DawoudSheraz commented on src/users/data/api.js
> +      });
why the return statement here? parsedData is by default []. How will that affect the parsing and existing SSO component?

2021-09-08 17:18 UTC, DawoudSheraz commented on src/users/v2/SingleSignOnRecordCard.test.jsx
> +  for (let index = 0; index < ssoRecords.length; index++) {
why use for loop? You can use jest test.each to repeat the tests by modifying the data. Ref: https://jestjs.io/docs/api#testeachtablename-fn-timeout

Also, using for loop to wrap a lot of test operations seems tricky. Do you have any examples/resources that advocate for this approach?

2021-09-08 17:18 UTC, DawoudSheraz commented on src/users/data/api.js
> +
won't we need to update the existing SSO component to accommodate this change??

2021-09-10 13:16 UTC, Ali-D-Akbar reviewed
Please rebase this branch onto master and add the component in UserSummary.jsx. It is kind of hard to verify the changes and the use-cases on local without it.

2021-09-10 13:16 UTC, Ali-D-Akbar commented on src/users/v2/SingleSignOnRecordCard.jsx
> +    ssoRecord ? (
Are we not going to show the loader here? This approach won't even show the column headings incase of no ssoRecords.

2021-09-10 13:16 UTC, Ali-D-Akbar commented on src/users/v2/SingleSignOnRecordsList.jsx
> +export default function SingleSignOnRecordsList({ username }) {
As said before, it'd be better to keep `SingleSignOnRecords.jsx` for the consistency: https://github.com/edx/frontend-app-support-tools/pull/145#discussion_r704145615

2021-09-10 17:09 UTC, DawoudSheraz commented on src/users/v2/SingleSignOnRecordCard.jsx
> +    ssoRecord ? (
Column headings are not fixed. They depend upon the received data from the API.

2021-09-13 15:02 UTC, ansabgillani commented on src/users/v2/SingleSignOnRecordsList.jsx
> +export default function SingleSignOnRecords({ username }) {
React filename/component naming convention not followed:
Component should be renamed to SingleSignOnRecordsList

2021-09-13 15:19 UTC, Ali-D-Akbar requested changes
1. There seem to have some overlapping text in this:
<img width="994" alt="Screenshot 2021-09-13 at 8 09 25 PM" src="https://user-images.githubusercontent.com/52413434/133110005-30323f71-25db-4e65-bffb-21bbaf47683d.png">

2. Two SSO cards in one row? Isn't one SSO record each row the right way according to AC?
<img width="1604" alt="Screenshot 2021-09-13 at 8 09 37 PM" src="https://user-images.githubusercontent.com/52413434/133110438-3ccefcfb-0f1a-4970-b4db-39c256813903.png">

3. Too much spacing above and below the fields in the 2nd screenshot.
4. In the AC, we see a card with only lower border. It'd be better to keep the consistency here as both enrollment and entitlement components use the same approach
![image](https://user-images.githubusercontent.com/52413434/133110925-8f65e609-8f09-4802-8730-75a079f0afc3.png)

2021-09-13 15:29 UTC, DawoudSheraz commented
@Ali-D-Akbar 
1. Yes, no overlapping text.
2. what width settings were used? Ideally, one record/card per row.
3. Can't quite understand this point.
4. Enrollments and Entitlements are using Table. SSO can't use table because extra data/metadata varies from provider. SSO is using card component, so that is why there will be extra border. 
5. Noted.

2021-09-13 17:08 UTC, ansabgillani commented
@DawoudSheraz Clarification on 3. 
Consider the top and bottom padding on the either. 

How it is supposed to look: 
<img width="960" alt="Screenshot at Sep 13 22-07-52" src="https://user-images.githubusercontent.com/56605828/133126945-0ba22a11-225c-4fa5-8e35-ca924d575b72.png">

How it actually looks:
<img width="691" alt="Screenshot at Sep 13 22-05-04" src="https://user-images.githubusercontent.com/56605828/133126799-daf215e8-3876-4b1b-a48e-89261c00ef4e.png">

2021-09-13 17:16 UTC, ansabgillani commented
Can you please verify if following is okay as it is currently or not:

1. Left align mismatch of the "Additional Data" and the elements in the table.
2. Proper alignment of copy and show to left and right ends respectively of their columns.
3. Small nits like bold texts and text fonts are yet to be addressed.
4. Note that in previous screenshot, "PM" is going on the next line instead of same line despite the same number of characters causing an extra bit of margin space.

2021-09-15 06:44 UTC, Ali-D-Akbar approved these changes
Looks good to me. 👍

2021-09-15 06:44 UTC, Ali-D-Akbar commented on src/users/v2/SingleSignOnRecordCard.test.jsx
> +describe.each(ssoRecordsData)('SSO Records', (ssoRecordData) => {
nit: Single Sign on Record Card.

2021-09-15 09:07 UTC, merged