feat: add entitlementV2 component
openedx-unsupported/frontend-app-support-tools pull request #146
Opened 2021-09-09 15:17 UTC by Ali-D-Akbar

[PROD-2463](https://openedx.atlassian.net/browse/PROD-2463)

This PR adds a new design for Entitlement Component while keeping the older components. This v2 component uses the new Table component that we used in Enrollment v2 component.

One Entitlement:
![image](https://user-images.githubusercontent.com/52413434/132713838-4c333180-a78b-4d0d-996f-f0c04fd9c558.png)

Entitlement with support details:
![image](https://user-images.githubusercontent.com/52413434/132713547-3bee3343-2ee0-425b-bb98-fc7a198985c7.png)

No Entitlement:
<img width="990" alt="Screenshot 2021-09-09 at 8 16 47 PM" src="https://user-images.githubusercontent.com/52413434/132713762-8a0e9f1e-9f49-4b10-a3b3-f15f1d28d309.png">

2021-09-09 15:55 UTC, DawoudSheraz reviewed
the changes look good on the surface. I have not tested it on local yet. Address the suggested changes before the final approval.

2021-09-09 15:55 UTC, DawoudSheraz commented on src/users/entitlements/v2/Entitlements.jsx
> +      modified: formatDate(entitlement.modified),
keep the sequence and column titles the same as the design.

2021-09-09 15:55 UTC, DawoudSheraz commented on src/users/entitlements/v2/Entitlements.jsx
> +              disabled={Boolean(!entitlement.enrollmentCourseRun)}
Does disable work with item? Instead of disabling it, we can skip the item altogether if the action is not applicable.

2021-09-09 15:55 UTC, DawoudSheraz commented on src/users/entitlements/v2/Entitlements.jsx
> +              Reissue
Lets use full words, like Reissue Entitlement

2021-09-09 18:24 UTC, Ali-D-Akbar commented on src/users/entitlements/v2/Entitlements.jsx
> +              Reissue
Hmm, I think it's pretty obvious that this action is specific to an entitlement.

2021-09-09 18:26 UTC, Ali-D-Akbar commented on src/users/entitlements/v2/Entitlements.jsx
> +              disabled={Boolean(!entitlement.enrollmentCourseRun)}
This is how it works. Reissue is disabled and expired is enabled. I think it still makes sense to keep the action there just so the support user knows how many actions are possible on each entitlement.

<img width="193" alt="Screenshot 2021-09-09 at 11 25 44 PM" src="https://user-images.githubusercontent.com/52413434/132741999-86be7d8b-a3cc-4afd-86d9-8f35cc4a448d.png">

2021-09-10 06:30 UTC, DawoudSheraz commented on src/users/entitlements/v2/Entitlements.jsx
> +              Reissue
Yes, it is. But take an example of the course dashboard. We see the Resume Course button there. Only Resume would have been enough too. Having explicit words is better.

2021-09-10 16:45 UTC, DawoudSheraz commented on src/index.jsx
> +          <Route path="/usersv2" component={UserPageV2} />
comment this out.

2021-09-10 16:50 UTC, DawoudSheraz requested changes
Enrollment Date and Course Run ID are two distinct headers. The course run ID column is missing.

2021-09-10 18:21 UTC, Ali-D-Akbar commented
> Enrollment Date and Course Run ID are two distinct headers. The course run ID column is missing.

<img width="1605" alt="Screenshot 2021-09-10 at 11 21 10 PM" src="https://user-images.githubusercontent.com/52413434/132899673-e277281a-1854-4d60-b5e4-125a39a6d49e.png">
Added course run ID and removed enrollment date for now as we don't receive this from backend.

2021-09-13 09:36 UTC, DawoudSheraz approved these changes

2021-09-13 09:36 UTC, DawoudSheraz commented on src/users/entitlements/v2/Entitlements.jsx
> +        // eslint-disable-next-line react/prop-types
is this necessary?

2021-09-13 09:36 UTC, DawoudSheraz commented
squash the commits before merging.

2021-09-13 09:58 UTC, Ali-D-Akbar commented on src/users/entitlements/v2/Entitlements.jsx
> +        // eslint-disable-next-line react/prop-types
Yes, react/prop-types eslint rule says every function must have their prop-types defined. This is a callback so we may not know what each row has.

2021-09-13 11:14 UTC, merged