feat: add loader and submit button features
openedx-unsupported/frontend-app-support-tools pull request #159
Opened 2021-10-05 12:48 UTC by Ali-D-Akbar

1. Shows a loader whenever submit button is pressed until the request is completed (also avoids multiple patch/post requests)
2. Submit button is hidden for all actions except create
3. New Mode input updated. Now it doesn't include the active enrollment mode.
![image](https://user-images.githubusercontent.com/52413434/136025013-2d138255-0d74-457f-8721-d6bd6ab6b265.png)

2021-10-05 15:52 UTC, DawoudSheraz commented on src/users/entitlements/v2/ExpireEntitlementForm.jsx
> +          ),
Please add a relevant test for it or update an existing test to properly test this.

2021-10-05 15:52 UTC, DawoudSheraz commented on src/users/entitlements/v2/ReissueEntitlementForm.jsx
> +          ),
same here.

2021-10-05 15:53 UTC, DawoudSheraz requested changes
to add missing unit tests.

2021-10-06 10:03 UTC, azanbinzahid approved these changes

2021-10-06 10:21 UTC, DawoudSheraz approved these changes
rebase before the merge.

2021-10-06 10:30 UTC, merged