fix: FBE same course consecutive search
openedx-unsupported/frontend-app-support-tools pull request #165
Opened 2021-10-15 06:09 UTC by ansabgillani

### [PROD-2511](https://openedx.atlassian.net/browse/PROD-2511)

### Description

- Fixing API call on search click with the same course

2021-10-15 12:37 UTC, Ali-D-Akbar approved these changes
Fair solution for the problem but can we do something other than sending a prop in FeatureBasedEnrollment component? It seems to add an extra unnecessary layer of dependability whenever we use it.

2021-10-15 12:53 UTC, ansabgillani commented
> Fair solution for the problem but can we do something other than sending a prop in FeatureBasedEnrollment component? It seems to add an extra unnecessary layer of dependability whenever we use it.

The idea behind this solution was to get a signal from the FBEIndexPage (Parent) to FBE (Child) component so it can make the API call whenever the search button was clicked. I don't see any other workaround than props to pass the signal.

2021-10-16 15:22 UTC, azanbinzahid commented
Just a thought, what if we re-render the component from [index page](https://github.com/edx/frontend-app-support-tools/blob/master/src/FeatureBasedEnrollments/FeatureBasedEnrollmentIndexPage.jsx) based on loading state instead of passing it as a prop?

2021-10-18 05:48 UTC, ansabgillani commented
> Just a thought, what if we re-render the component from [index page](https://github.com/edx/frontend-app-support-tools/blob/master/src/FeatureBasedEnrollments/FeatureBasedEnrollmentIndexPage.jsx) based on loading state instead of passing it as a prop?

@azanbinzahid tried this but did not work. The problem I am facing is that the API call is being called in the child component and should be dependent on a signal from the parent. Even if I re-render the component, the useEffect still requires a signal from the parent.

2021-10-25 08:49 UTC, DawoudSheraz requested changes
- Missing related unit test
- It seems the loading state is not loading but acting as a toggle so that useEffect can be triggered. We should rename it so that it does not give an impression of loading data.

2021-10-25 11:14 UTC, ansabgillani commented
Follow up on this. According to the react way, the best and most convenient way to approach this problem is to form up a signal that fires the useEffect triggering an API call in the child component. 

https://github.com/facebook/react/issues/6646#issuecomment-215580357

2021-10-26 09:32 UTC, DawoudSheraz approved these changes
- Squash the commits and rebase the branch
- Address one nit

2021-10-26 09:32 UTC, DawoudSheraz commented on src/FeatureBasedEnrollments/FeatureBasedEnrollmentIndexPage.test.jsx
> +      .mockImplementation(() => Promise.resolve(fbeEnabledResponse));
nit: keep this all on the same line and only extend if the line length is violated.

2021-10-26 19:42 UTC, azanbinzahid approved these changes

2021-10-27 08:05 UTC, merged