feat: using edx/reactifex for push translations
openedx-unsupported/frontend-app-support-tools pull request #168
Opened 2021-10-29 09:58 UTC by DawoudSheraz

### [PROD-2526](https://openedx.atlassian.net/browse/PROD-2526)

### Description

- Add edx/reactifex as dependency and use Transifex api v3 scripts for push translation
- Update frontend-platform to the latest version to be compatible with edx/reactifex
- Add 2 FormattedMessage elements for testing the push translation
- Add Transifex config file

Note that the push translations will be tested through the Jenkins job.

### Links

- https://github.com/edx/frontend-platform/blob/master/docs/how_tos/i18n.rst
- https://openedx.atlassian.net/wiki/spaces/LOC/pages/3103293538/MFE+Translation+How+To+s
- https://openedx.atlassian.net/wiki/spaces/IM/pages/3219324929/Using+edx+reactifex+in+push+translation+script+for+MFEs

2021-10-29 13:25 UTC, davidjoy requested changes

2021-10-29 13:25 UTC, davidjoy commented on package.json
> +    "react-intl": "^5.21.0",
This is a dependency of frontend-platform, so it doesn't need to be added in the app itself.

2021-10-29 13:32 UTC, DawoudSheraz commented on package.json
> +    "react-intl": "^5.21.0",
I was getting both unit tests failure and eslint unresolved import error if I was not adding it as a dependency. Some other repos([ora-grading](https://github.com/edx/frontend-app-ora-grading/blob/7e99e7cca29568afcb4347f587411aed6c1e9e7f/package.json), [special-exams](https://github.com/edx/frontend-lib-special-exams/blob/f0eaf4faad48831f17876d8bc47c14d46bdcc92d/package.json)) had both frontend-platform and react-intl as dependency.

2021-10-29 14:20 UTC, davidjoy commented on package.json
> +    "react-intl": "^5.21.0",
I'm not sure what ora-grading and special-exams are doing, but they shouldn't have react-intl as a direct dependency.  That sounds like a mistake as well.  Everything should be imported from `@edx/frontend-platform/i18n`, rather than from `react-intl`.  frontend-platform re-exports everything because we have some shims and wrappers around some of the components, and also because you can only have one version of react-intl running at a time or it won't work.

Any imports from `'react-intl`' should be replaced with `'@edx/frontend-platform/i18n'`, even in tests, and then the dependency can be removed.

2021-10-29 15:47 UTC, DawoudSheraz commented on package.json
> +    "react-intl": "^5.21.0",
Removed `react-intl` as a dependency and importing the provider from frontend-platform now.

2021-11-01 08:58 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +                  email: <b>{email}</b>,
will it pick b tag automatically?

2021-11-01 09:11 UTC, azanbinzahid approved these changes

2021-11-01 09:11 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +                  email: <b>{email}</b>,
Will it pick `b` tag automatically given we are providing `tagName` separately?

2021-11-01 09:26 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +                  email: <b>{email}</b>,
Yes, **values** contain the individual value for the variables defined in the message.

2021-11-01 09:29 UTC, ansabgillani approved these changes

2021-11-01 09:41 UTC, Ali-D-Akbar approved these changes
Are these all the messages in Support Tools that are subjected to translation?

2021-11-01 13:05 UTC, DawoudSheraz commented
> Are these all the messages in Support Tools that are subjected to translation?

There might be 1-2 more but they will be added/tested in a follow-up PR to verify the new scripts also work well with existing and new translation strings.

2021-11-01 14:59 UTC, davidjoy commented on src/users/account-actions/v2/ResetPassword.jsx
> +                  email: <b>{email}</b>,
Nit: I think we want to avoid using `<b>` and use `<strong>` instead - the latter carries semantic meaning for accessibility devices, which I think we want here.

2021-11-02 08:17 UTC, DawoudSheraz commented
@davidjoy can you take a look, please? It seems I can't merge the PR unless the requested changes are addressed, which I have done already.

2021-11-02 11:13 UTC, davidjoy approved these changes

2021-11-02 16:10 UTC, merged