feat: use enrollment date as default sort column
openedx-unsupported/frontend-app-support-tools pull request #198
Opened 2021-11-22 12:15 UTC by Ali-D-Akbar

[PROD-2575](https://openedx.atlassian.net/browse/PROD-2575)
Use Enrollment Date as an initial sort column in Enrollment table to show the most recent enrolled course at the top of the list by default.

2021-11-22 12:57 UTC, DawoudSheraz commented on src/components/Table.jsx
> +      },
Instead of hard-coding default sort to be desc, the component using the TableV2 should decide if the default sort is needed and in what direction.

2021-11-22 12:59 UTC, DawoudSheraz requested changes
Let the component utilizing TableV2 decide if the default sort is needed in a particular direction. The hard-coding of default sort is not a scalable solution. This is also causing the test failures.

2021-11-23 06:28 UTC, DawoudSheraz approved these changes
Please uncommit package-lock.json before merge.

2021-11-23 07:35 UTC, ansabgillani approved these changes

2021-11-23 07:59 UTC, azanbinzahid approved these changes

2021-11-23 08:53 UTC, merged