feat: add link program enrollment to v2
openedx-unsupported/frontend-app-support-tools pull request #200
Opened 2021-12-13 23:09 UTC by ansabgillani

This is a Support upgrade ticket that introduces a new interface for Link program Enrollments.

Link to the ticket: [PROD-2478](https://openedx.atlassian.net/jira/software/c/projects/PROD/boards/507?modal=detail&selectedIssue=PROD-2478)

Testing Methodology:
- Make a program using this document: [How to enable Programs on Devstack](https://openedx.atlassian.net/wiki/spaces/PT/pages/3034218678/How+to+enable+Programs+on+Devstack)
- Go to LMS Admin and [create a program enrollment](http://localhost:18000/admin/program_enrollments/programenrollment/add/) for a current user.
- Go to LMS support tools and [verify if linkages](http://localhost:18000/support/link_program_enrollments) are being created for the program enrollments. (Optional)
- Go to the new interface for Support tools and open the tab ["Program Enrollments"](http://localhost:18450/v2/program_enrollment) and make a linkage. You can also verify if the program enrollments are being created in the LMS admin.

2021-12-14 09:56 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +        console.log(programID)
remove the log statement

2021-12-14 09:58 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +        console.log(usernamePairText)
to remove the log statement

2021-12-14 10:00 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.jsx
> +        return text.split(",")
Please add a JSDoc explaining why is this extraction needed.

2021-12-14 10:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.jsx
> +        text = text.replaceAll(" ", '')
these can be chained together.

2021-12-14 10:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.jsx
> +                        itemCount={successMessage.length}
success count used in error table.

2021-12-14 10:04 UTC, DawoudSheraz commented on src/ProgramEnrollments/data/api.js
> +    console.log(usernamePairText);
log statement to be removed.

2021-12-14 10:05 UTC, DawoudSheraz requested changes
- Please use tablev2 for rendering tables
- Disable submit button when it is clicked to avoid any accidental clicks resulting in successive API calls.
- nits/changes to be addressed added.

2021-12-14 13:49 UTC, ansabgillani commented
@DawoudSheraz addressed nits. Linting issues are yet to be addressed once tests are written.

2021-12-14 19:02 UTC, azanbinzahid requested changes

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +        setProgramID(e.currentTarget.value)
I think we need to validate or sanitize user inputs before making API call.

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +        setUsernamePairText(e.currentTarget.value)
same as above.

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.jsx
> +  function extractMessageTuple(message) {
this can be moved to utils.

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.jsx
> +        The support tools server sends an array of tuples of format
did we write this? if yes, we can update server logic. Otherwise its fine for now.

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.jsx
> +              return {
this can be reduced to one liner

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/ProgramEnrollmentsIndexPage.jsx
> +import React from 'react';
this filename can just be `index.js`?

2021-12-14 19:02 UTC, azanbinzahid commented on src/ProgramEnrollments/data/api.js
> +export default async function getLinkProgramEnrollmentDetails({
the api call here is little out of the repos's folder structure but I like the idea.

2021-12-14 19:02 UTC, azanbinzahid commented on src/SupportToolsTab/SupportToolsTab.jsx
> +      break;
Please add a `default` case or remove last `break`.

2021-12-14 19:02 UTC, azanbinzahid commented on src/index.jsx
> +          <Route path="/v2/program_enrollments" comnponent={ProgramEnrollmentsIndexPage} />
we may take these paths directly from path mapping that we have.

2021-12-14 19:02 UTC, azanbinzahid commented on src/overrides.scss
> +.link-program-enrollments {
is it for table, some div or error? please specify.

2021-12-15 13:25 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +        setProgramID(e.currentTarget.value)
+1 on this.

2021-12-15 13:25 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +        setUsernamePairText(e.currentTarget.value)
same here.

2021-12-20 12:00 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramEnrollmentsIndexPage.jsx
> +import React from 'react';
I don't think it will make sense considering the React convention is the same filename for component name

2021-12-20 12:01 UTC, ansabgillani commented on src/overrides.scss
> +.link-program-enrollments {
It's for the link-program-enrollments component (div)

2021-12-20 15:08 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +  };
to add validation on these inputs before setting the state variables.

2021-12-20 15:09 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +              List of Username Text (one per line)
nit: List of External key and username pairings

2021-12-20 15:11 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +  };
prevent default event here to avoid any side-effects that might pop-up

2021-12-20 15:12 UTC, DawoudSheraz commented on src/overrides.scss
> +}
nit: end of file line missing.

2021-12-20 15:13 UTC, DawoudSheraz commented on src/utils/index.js
> +export function extractMessageTuple(message) {
to add unit tests for this util.

2021-12-20 15:16 UTC, DawoudSheraz commented on src/ProgramEnrollments/data/api.test.js
> +      .onPost(lpeDetailsApiUrl, data)
hmm, did that work right away? I remember facing issues in past when mocking post call that sending post data as form data.

2021-12-20 15:17 UTC, DawoudSheraz commented on src/ProgramEnrollments/data/api.test.js
> +describe('Feature Based Enrollment API', () => {
nit: to update the description of this test.

2021-12-20 15:23 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollmentsTable.test.jsx
> +      );
all the error tests are varying in terms of input and expected error messages. In this case, jest's test.each can be used to unify the code and only change the data, much like ddt in python(https://jestjs.io/docs/api#testeachtablename-fn-timeout)

2021-12-20 15:24 UTC, DawoudSheraz reviewed
added small nits/update comments.

2021-12-21 16:15 UTC, DawoudSheraz commented on src/ProgramEnrollments/LinkProgramEnrollments.jsx
> +      setUsernamePairText(undefined);
nit: setProgramID(undefined) instead of usernamepairtext.

2021-12-21 16:17 UTC, DawoudSheraz commented on src/ProgramEnrollments/data/api.test.js
> +describe('Feature Based Enrollment API', () => {
@ansabgillani to update the description of this.

2021-12-21 16:18 UTC, DawoudSheraz approved these changes
nits to address before merge.

2021-12-22 08:20 UTC, Ali-D-Akbar approved these changes
There might be some comments to address before. Looks good to me from my end. 👍

2021-12-22 10:18 UTC, azanbinzahid approved these changes

2021-12-23 12:47 UTC, merged