Add enterprise course enrollments data
openedx-unsupported/frontend-app-support-tools pull request #205
Opened 2022-01-10 22:11 UTC by long74100

- Add enterprise course enrollments data to each course enrollment

![Screen Shot 2022-01-10 at 5 10 37 PM](https://user-images.githubusercontent.com/17792243/148847090-47225366-3e26-42b0-9d01-349e60c70f22.png)

2022-01-11 16:21 UTC, macdiesel approved these changes

2022-01-21 16:39 UTC, manny-m approved these changes
LGTM 👍

2022-01-24 09:30 UTC, Ali-D-Akbar approved these changes
One nit although not a blocker. 👍

2022-01-24 09:30 UTC, Ali-D-Akbar commented on src/users/data/test/enrollments.js
> +        saved_for_later: false,
`saved_for_later: false` is never used in the component so perhaps this can be removed for the test.

2022-01-24 13:51 UTC, DawoudSheraz commented on src/users/enrollments/v2/Enrollments.jsx
> +        />
add a divider between these two tables for better readability.

2022-01-24 13:52 UTC, DawoudSheraz commented on src/users/enrollments/v2/Enrollments.jsx
> +                },
For the sake of consistency, please define these column values in a variable and use the variable here.

2022-01-24 13:53 UTC, DawoudSheraz commented on src/users/enrollments/v2/Enrollments.test.jsx
> +  it('Enrollment extra data and enterprise course enrollments are rendered for individual enrollment', () => {
please add a unit test that checks Table is not rendered for Enterprise course enrollments if the data is not present in the API.

2022-01-24 13:55 UTC, DawoudSheraz requested changes
Small updates and a unit test case to add. Otherwise, the changes are good.

2022-01-25 13:32 UTC, DawoudSheraz approved these changes
Good to merge once the build is green.

2022-01-25 15:25 UTC, merged