feat: Add filter for enrollment and entitlements
openedx-unsupported/frontend-app-support-tools pull request #209
Opened 2022-01-13 19:40 UTC by AliAdnanSohail

[add course id and title based frontend filtering on enrollment/entitlement page](https://openedx.atlassian.net/browse/PROD-2547)
<img width="1428" alt="Screen Shot 2022-01-14 at 12 40 03 AM" src="https://user-images.githubusercontent.com/15185149/149397916-32e818bd-d08d-49af-bf6e-572ba0b58829.png">

2022-01-17 11:17 UTC, DawoudSheraz commented on src/users/enrollments/v2/Enrollments.jsx
>        expander: {
Please add an appropriate unit tests for this condition in Enrollments and Entitlements V2 ccomponents

2022-01-17 11:19 UTC, DawoudSheraz commented on src/users/EntitlementsAndEnrollments.jsx
> +        <Button name="courseSearch" className="ml-1 col-sm-1" variant="primary" onClick={() => { setSearchValue(searchStr.toLowerCase()); }}>Search</Button>
Since the search is not making any API call, I would suggest filtering as we type instead of having to press/click Submit.

2022-01-17 11:22 UTC, DawoudSheraz requested changes
- Add unit tests in Enrollment v2 and Entitlement v2 for searchStr filtering checks as the filter is added in those components and the wrapper component is just passing the value to them
- Use onChange of input to filter instead of having to click
- Rename EntitlementsAndEnrollments, maybe EnrollmentEntitlementSearchWrapper, EnrollmentEntitlementSearchContainer etc.

2022-01-17 11:33 UTC, AliAdnanSohail commented on src/users/EntitlementsAndEnrollments.jsx
> +        <Button name="courseSearch" className="ml-1 col-sm-1" variant="primary" onClick={() => { setSearchValue(searchStr.toLowerCase()); }}>Search</Button>
@DawoudSheraz Actually I was following design mockup mentioned in this ticket
https://openedx.atlassian.net/browse/PROD-2547
Should i remove this search button?

2022-01-17 15:57 UTC, DawoudSheraz approved these changes

2022-01-17 22:01 UTC, azanbinzahid approved these changes

2022-01-18 06:54 UTC, ansabgillani approved these changes

2022-01-18 13:36 UTC, merged