feat: add program inspector to new support tools
openedx-unsupported/frontend-app-support-tools pull request #213
Opened 2022-01-19 08:57 UTC by ansabgillani

2022-02-08 14:39 UTC, Ali-D-Akbar reviewed
Can we add a heading to indicate what this id means?
<img width="234" alt="Screenshot 2022-02-08 at 7 37 50 PM" src="https://user-images.githubusercontent.com/52413434/153009007-243625f5-ad37-4be2-a892-eaf823340ee8.png">

2022-02-08 14:39 UTC, Ali-D-Akbar commented on .env.development
> +STUDIO_BASE_URL = 'http://localhost:18010'
Newline please. https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-02-08 14:39 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +          ]}
Write these columns out of the table to improve readability.

2022-02-08 14:39 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +            ]}
Write these columns out of the table to improve readability.

2022-02-08 14:39 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspectorSearch.jsx
> +  };
Can we not do this directly in the Input component?

2022-02-08 14:39 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspectorSearch.jsx
> +  };
Same question for the rest of these.

2022-02-09 04:57 UTC, ansabgillani commented
@Ali-D-Akbar These are Program Name and Program UUID for the enrolled person.

2022-02-09 05:05 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspectorSearch.jsx
> +  };
Tried improving the readability on the code.

2022-02-10 06:01 UTC, DawoudSheraz requested changes
- Awaiting tests to go green
- Code readability issues across various files
- Design/rendering changes

2022-02-10 06:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramEnrollmentsIndexPage.jsx
> +
this piece of code is very hard to read. Please improve it.

2022-02-10 06:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramEnrollmentsIndexPage.jsx
> +        </>
I would suggest rendering link enrollment and inspector side by side instead of just rendering inspector details after the search query. Otherwise the support will have to reload the entire page to show the components again.

2022-02-10 06:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +import courseColumns from './utils/CourseDetailsColumns.json';
I would suggest having these as constant variables in contants.js instead of separate JSON files.

2022-02-10 06:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +                  >
Why are we redirecting to studio instead of LMS?

2022-02-10 06:01 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.test.jsx
> +        }
please update the code readability here.

2022-02-18 15:56 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/utils/CourseDetailsColumns.json
> +  }
Please convert this JSON into a variable and keep it in constants.js. Same for EnrollmentDetailsColumns.json file.

2022-02-23 18:15 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +                mode: courseEnrollment.course_enrollment.mode,
it is possible for course enrollment to be undefined/missing. Add safe checks here, otherwise the component and page breaks(attempting to find course_id on null)

2022-02-23 18:18 UTC, DawoudSheraz commented on .env
> +STUDIO_BASE_URL = null
why is STUDIO_BASE_URL added? I don't see any usage across the modified files.

2022-02-23 18:27 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramEnrollmentsIndexPage.jsx
> +        }
the location would need to update when the tabs are switched.

2022-02-23 18:28 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/utils/CourseDetailsColumns.js
> +export default CourseColumns;
please move this and src/ProgramEnrollments/ProgramInspector/utils/EnrollmentDetailsColumns.js to constants.js instead of having dedicated files for them.

2022-02-23 18:29 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.test.jsx
> +  it('Enrollment Details no render', async () => {
nit: enrollment details do no render

2022-02-23 18:30 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.test.jsx
> +  it('Enrollment Details no render', async () => {
this has the same name as the previous test. You can combine them with it.each/test.each as both tests are achieving similar things.

2022-02-23 18:31 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.test.jsx
> +  it('Program course enrollments table render True Audit', async () => {
same, this and the next test can be combined. There is some minor differences that can be handled dynamically.

2022-02-23 18:34 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +  const [orgKey, setOrgKey] = useState(params.get('org_key'));
nit: active or selected orgKey will help differentiate from orgKeyList

2022-02-23 18:36 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +          if (data.provider === orgKeys) {
why is provider compared to orgKeys?

2022-02-23 18:38 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +            Search Program
nit: Search Program Records

2022-02-23 18:39 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +                  <p className="h5">{learnerProgramEnrollment.user.username}</p>
the username/email values should not be h5.

2022-02-23 18:39 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +            </div>
no need for IDV, it has been removed.

2022-02-23 18:40 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +          </div>
Give indication if no sso record is found. otherwise, the user would not know if SSO record is missing or not displayed by the component

2022-02-23 18:45 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.test.jsx
> +    wrapper.find('button.btn-primary').simulate('click');
nit: the code is weirdly formatted here.

2022-02-23 18:46 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.test.jsx
> +    );
we should verify some data rendering too. Only checking against this mock is not enough.

2022-02-23 18:54 UTC, DawoudSheraz reviewed
added various comments.

2022-02-25 04:50 UTC, ansabgillani commented on .env
> +STUDIO_BASE_URL = null
It was added because previously the courses were being linked to studio. It's been removed now.

2022-02-25 04:51 UTC, ansabgillani commented on .env
> +STUDIO_BASE_URL = null
Will remove it in following commit.

2022-02-25 04:53 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +                mode: courseEnrollment.course_enrollment.mode,
Actually, it never returns null if a course enrollment exists. Nevertheless, I'll add the checks.

2022-02-25 04:56 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +          if (data.provider === orgKeys) {
So, whenever we fetch SSORecords, it returns all SSO records from the current API call. We just want the SSO record for the current organization.

2022-02-25 04:58 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +            </div>
There is an IDV status component in the wireframes. What's the alternate?

2022-02-25 05:01 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.test.jsx
> +    wrapper.find('button.btn-primary').simulate('click');
Will improve

2022-02-28 05:07 UTC, Ali-D-Akbar reviewed
Some suggestions. Otherwise, looks good to me.

2022-02-28 05:07 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +  const [orgKeys, setOrgKeys] = useState(undefined);
Confusing naming between orgKeys, orgKey, orgKeyList. Can we do something about it?

2022-02-28 05:07 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspector/utils/EnrollmentDetailsColumns.js
> +export default EnrollmentColumns;
Move this to constants as well.

2022-02-28 05:07 UTC, Ali-D-Akbar commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +          {enrollment.program_name} ({enrollment.program_uuid})
Add some sort of a heading indicating what this is. One can't understand right away if the enrollment doesn't have a `program_name`.

2022-03-02 05:01 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +  const [orgKeys, setOrgKeys] = useState(undefined);
Removed the issue with refactoring.

2022-03-02 05:01 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +  const [orgKey, setOrgKey] = useState(params.get('org_key'));
Removed the issue with refactoring.

2022-03-02 08:14 UTC, DawoudSheraz reviewed
Nits or refactors to be done before final approval

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +      <div key={enrollment.program_name} className="enrollments">
we can use program_name - program_uuid combo for key, or simply program uuid.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +              (courseEnrollment) => ({
nit: courseEnrollment -> programCourseEnrollment

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +                mode: courseEnrollment.course_enrollment.mode,
Safe checks on courseEnrollment.course_enrollment to be added i.e. if course_enrollment is not present, accessing the course_id, is_active, mode, will cause component breakage.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.test.jsx
> +    'Enrollment Details does not render',
nit: do not

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +    }
Set ssoRecord to null if no value is found or user is not defined. Otherwise the card will remain there from previous searches

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +            Search Program
This is yet to be addressed.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +                  <p className="h5">{learnerProgramEnrollment.user.username}</p>
This is also not addressed.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +              </div>
give some indicator here if no SSO record is present or ssoRecord is undefined.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +          </div>
Not addressed, re-added the comment above.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.test.jsx
> +    wrapper.find('button.btn-primary').simulate('click');
not addressed.

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.test.jsx
> +    );
Verify some data values here too

2022-03-02 08:14 UTC, DawoudSheraz commented on src/ProgramEnrollments/ProgramInspector/utils/CourseDetailsColumns.js
> +export default CourseColumns;
this is also not addressed.

2022-03-02 13:13 UTC, azanbinzahid requested changes
A general feedback after running changes locally:

- Please improve UI by adding enrollments inside program rows with expendable button and consistent design 
- Fix search button / url params error
- Replay last state on tab change untill search button is pressed
- Mention errors/issues about backend in PR

2022-03-04 06:15 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/EnrollmentDetails.jsx
> +                mode: courseEnrollment.course_enrollment.mode,
I checked the backend for this. This is always going to be sent by the API if the course enrollment against a program enrollment exists.

2022-03-04 07:02 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.test.jsx
> +    );
Done

2022-03-04 08:24 UTC, ansabgillani commented
Updated Screenshot: 
![Uploading Screenshot 2022-03-04 at 1.23.46 PM.png…]()

2022-03-04 08:25 UTC, ansabgillani commented on src/ProgramEnrollments/ProgramInspector/ProgramInspector.jsx
> +    }
Done

2022-03-04 10:19 UTC, DawoudSheraz approved these changes
some missing code coverage places that can be catered via follow-up PR.

2022-03-04 11:10 UTC, Ali-D-Akbar approved these changes

2022-03-07 10:25 UTC, azanbinzahid approved these changes

2022-03-07 13:23 UTC, merged