feat: display error response on password reset
openedx-unsupported/frontend-app-support-tools pull request #214
Opened 2022-01-25 14:26 UTC by AliAdnanSohail

[show reset password api response on dialog](https://openedx.atlassian.net/browse/PROD-2600)

<img width="1429" alt="Screen Shot 2022-01-25 at 7 25 59 PM" src="https://user-images.githubusercontent.com/15185149/150995074-2cd6cd31-d972-4487-a5c1-8d7908cf2a54.png">

2022-01-25 14:42 UTC, azanbinzahid requested changes

2022-01-25 14:42 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +      <Modal
I believe we can use the same model just render different body based on error status, will save a few lines of code.

2022-01-25 14:42 UTC, azanbinzahid commented on src/users/data/api.js
> +          text: error.response.data,
What kind of errors can we expect from this API? Will there be any case in which `error.response.data` will not be there in an error say `500`?

2022-01-25 14:42 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.test.jsx
> +  it('Display Error on Reset Password Modal', async () => {
You may need to test with all possible (or a few more) kind of errors.

2022-01-25 14:42 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +                values={{ errorMessage }}
Not sure what's the difference b/w the two `{{testString}}` or `"{testString}"`

2022-01-25 14:45 UTC, AliAdnanSohail commented on src/users/account-actions/v2/ResetPassword.jsx
> +                values={{ errorMessage }}
`defaultMessage` attribute should be translatable so we could not pass dynamic value in this. To pass dynamic value we have to interpolate that dynamic value and then pass that value in `values` attribute

2022-01-25 14:47 UTC, AliAdnanSohail commented on src/users/account-actions/v2/ResetPassword.test.jsx
> +  it('Display Error on Reset Password Modal', async () => {
Actually I've catch all type of errors which will be returned in `errors` object in same way. So we don't need to test different type of errors because only string will be different, everything else will be same.

2022-01-25 14:49 UTC, AliAdnanSohail commented on src/users/account-actions/v2/ResetPassword.jsx
> +      <Modal
Actually same modal contains some extra buttons and their click handlers. So either we need to add conditions to display or hide them, or we can handle this in separate modal. So I choose the second option

2022-01-25 14:51 UTC, AliAdnanSohail commented on src/users/data/api.js
> +          text: error.response.data,
Yes we can add a check if there is no error description and error.response.data is empty then we can display some generic message e.g `Something went wrong` may be

2022-01-25 15:00 UTC, Ali-D-Akbar reviewed
Overall the changes look good. Just add some tests to cover all the checks. There is some drop in the coverage.

2022-01-25 17:10 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +      <Modal
+1 to what Azan said. The button/click handlers will only be closing the modal and not doing anything special. We can also hide buttons under certain conditions too.

2022-01-25 17:13 UTC, DawoudSheraz reviewed
Most concerns have been raised by Azan already.

2022-01-25 21:44 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +                values={{ errorMessage }}
I believe we can avoid using formatted messages and use simple string. Please see relevant usage [here](https://github.com/openedx/frontend-app-support-tools/blob/76d3b5c5756bd0d9842817b247fe9a387d2cbd2a/src/users/enrollments/v2/Certificates.jsx).

2022-01-31 16:57 UTC, azanbinzahid approved these changes

2022-01-31 16:57 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +  const [resetPasswordError, setResetPasswordError] = useState(false);
We can use one state variable for both.

2022-01-31 16:57 UTC, azanbinzahid commented on src/users/account-actions/v2/ResetPassword.jsx
> +        buttons={[resetPasswordError ? ('')
you may return `null` or` <></>` as well.

2022-01-31 17:44 UTC, Ali-D-Akbar approved these changes

2022-02-01 07:35 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +  const [resetPasswordError, setResetPasswordError] = useState(false);
Yes, we can check the existence of the error from error message.

2022-02-01 07:36 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +        buttons={[resetPasswordError ? ('')
+1

2022-02-01 07:41 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +      changeHandler();
personally, I think we can remove this changeHandler and display some messages, such as a request is submitted. We can do this in a follow-up ticket and PR. Just flagging this now that it is in the works, we can go with fixing all behavioral inconsistencies. The page reloadiing after successful submission seems a bit weird now.

2022-02-01 07:41 UTC, DawoudSheraz approved these changes

2022-02-01 09:57 UTC, AliAdnanSohail commented on src/users/account-actions/v2/ResetPassword.jsx
> +      changeHandler();
@DawoudSheraz Actually its coming from props, and if we don't need the functionality of this specific method then we can simply close the modal and update message in modal

2022-02-01 10:19 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +      changeHandler();
Yes, something like that. We can remove submit button and only display a success/error message based on the response. Closing modal will be left to the user.

2022-02-01 10:23 UTC, AliAdnanSohail commented on src/users/account-actions/v2/ResetPassword.jsx
> +      changeHandler();
If you want me to handle in this ticket. I can do it here as well

2022-02-01 11:39 UTC, DawoudSheraz commented on src/users/account-actions/v2/ResetPassword.jsx
> +      changeHandler();
no, lets have a dedicated ticket and PR for that.

2022-02-01 12:19 UTC, merged