feat: Display verified-in and current-status data on onboarding status
openedx-unsupported/frontend-app-support-tools pull request #217
Opened 2022-02-08 13:44 UTC by AliAdnanSohail

2022-02-10 05:49 UTC, DawoudSheraz commented on src/users/data/test/onboardingStatus.js
> +  },
Shouldn't this be a separate data variable?

2022-02-10 05:50 UTC, DawoudSheraz commented on src/users/v2/OnboardingStatus.jsx
> +      { onboardingData ? (
how are we not changing API call here? We introduced a new endpoint in lms support app and would be using that, isn't it the case?
cc: @azanbinzahid

2022-02-10 05:50 UTC, DawoudSheraz requested changes
API call updates are missing.

2022-02-10 05:51 UTC, DawoudSheraz commented on src/users/v2/OnboardingStatus.jsx
> +      { onboardingData ? (
https://github.com/openedx/edx-platform/pull/29607 this is the PR/API I am referring to.

2022-02-15 21:02 UTC, azanbinzahid requested changes
I think we can now update/add call with new endpoint and complete this PR. Meanwhile, please keep this PR as draft.

2022-02-15 21:02 UTC, azanbinzahid commented on src/users/data/test/onboardingStatus.js
> +  },
+1
Please use a different variable with mock data.

2022-02-15 21:02 UTC, azanbinzahid commented on src/users/v2/OnboardingStatus.jsx
> +      { onboardingData ? (
This will be updated, it was done to fast-forward the implementation and must've been mentioned in PR description.

2022-02-22 10:44 UTC, azanbinzahid commented on src/users/data/api.js
> +    return defaultResponse;
may be we should return/display some kind of error as well.

2022-02-22 10:44 UTC, azanbinzahid commented on src/users/entitlements/v2/Entitlements.test.jsx
> +    it('Disabled Expire entitlement button', async () => {
Please add explanation as to why it was[n't] working.

2022-02-22 10:44 UTC, azanbinzahid commented on src/users/v2/OnboardingStatus.jsx
> +      status: result.onboardingStatus ? titleCase(result.onboardingStatus) : 'See Dashboard',
Please add a comment on why we are redirecting to dashboard.

2022-02-22 10:44 UTC, azanbinzahid commented on src/users/v2/OnboardingStatus.jsx
> +          ) : <div className="no-record-text" id="current-status-no-data">No Record Found</div>}
error can be displayed here

2022-02-22 16:51 UTC, DawoudSheraz commented on src/users/data/api.js
> +    return defaultResponse;
Yup, true.

2022-02-22 16:52 UTC, DawoudSheraz commented on src/users/v2/OnboardingStatus.jsx
> +          ) : <div className="no-record-text" id="current-status-no-data">No Record Found</div>}
The error returned in API response?

2022-02-22 16:57 UTC, DawoudSheraz commented on src/users/entitlements/v2/Entitlements.test.jsx
> +    it('Disabled Expire entitlement button', async () => {
Yeah, this was a weird one. When running a few test cases individually, the Entitlement component tests were constantly causing giving logs errors that async updates were being made. The DropDown component, which shows the possible actions on entitlement after click, was having its state updated internally after the test execution was complete. That's why I added wait after click to allow DropDown updates to complete before moving ahead.

2022-02-22 17:06 UTC, DawoudSheraz commented on src/users/v2/OnboardingStatus.jsx
> +      status: result.onboardingStatus ? titleCase(result.onboardingStatus) : 'See Dashboard',
Not sure why @AliAdnanSohail did that. We can maybe add a default status here instead of See Dashboard text.

2022-02-23 09:09 UTC, azanbinzahid commented on src/users/v2/OnboardingStatus.jsx
> +      status: result.onboardingStatus ? titleCase(result.onboardingStatus) : 'See Dashboard',
Actually I suggested this and having  comment in code will mitigate the confusion. There are certain status in db for which the api gives null/undefined value but they are visible on instructor dashboard.

2022-02-23 09:09 UTC, azanbinzahid commented on src/users/v2/OnboardingStatus.jsx
> +          ) : <div className="no-record-text" id="current-status-no-data">No Record Found</div>}
Yes

2022-02-23 09:59 UTC, DawoudSheraz commented on src/users/v2/OnboardingStatus.jsx
> +      status: result.onboardingStatus ? titleCase(result.onboardingStatus) : 'See Dashboard',
Right, makes sense.

2022-02-24 13:11 UTC, azanbinzahid approved these changes

2022-02-24 13:15 UTC, DawoudSheraz approved these changes

2022-02-24 13:16 UTC, merged