feat: show user message on retired email search
openedx-unsupported/frontend-app-support-tools pull request #233
Opened 2022-03-09 21:56 UTC by Ali-D-Akbar

TBA

2022-03-11 07:21 UTC, azanbinzahid requested changes

2022-03-11 07:21 UTC, azanbinzahid commented on src/users/data/api.js
> +    } else if (isEmail(userIdentifier)) {
I think we should just set `notFoundErrorText` here and follow the existing flow. Error is thrown after `if/else` block.

2022-03-11 09:05 UTC, azanbinzahid approved these changes

2022-03-11 09:05 UTC, azanbinzahid commented on src/users/data/api.js
> +      notFoundErrorText = JSON.parse(error.customAttributes.httpErrorResponseData).error_msg;
One more thing, you may need to check if these attrib exist or not, just to prevent any unexpected error.

2022-03-14 04:55 UTC, DawoudSheraz commented on src/users/data/api.js
> +    if (JSON.parse(error.customAttributes?.httpErrorResponseData)) {
?. what is this syntax?

2022-03-14 04:55 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +
A bit difficult to read here. Add the comment on why the error handling is needed here.

2022-03-14 05:28 UTC, Ali-D-Akbar commented on src/users/data/api.js
> +    if (JSON.parse(error.customAttributes?.httpErrorResponseData)) {
if `customAttributes` exists, get `httpErrorResponseData`.

2022-03-14 05:48 UTC, DawoudSheraz commented on src/users/data/api.js
> +    if (JSON.parse(error.customAttributes?.httpErrorResponseData)) {
Is this Es6 syntax? Seeing this for the first time.

2022-03-14 05:59 UTC, DawoudSheraz approved these changes
one small nit comment, otherwise good to go.

2022-03-14 06:30 UTC, Ali-D-Akbar commented on src/users/data/api.js
> +    if (JSON.parse(error.customAttributes?.httpErrorResponseData)) {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-03-14 07:48 UTC, Ali-D-Akbar commented on src/users/data/api.test.js
> +
improved readability and added a comment too.

2022-03-14 07:52 UTC, merged