feat:add SSO history to the SSO card
openedx-unsupported/frontend-app-support-tools pull request #237
Opened 2022-03-25 05:43 UTC by ansabgillani

2022-05-30 07:44 UTC, DawoudSheraz reviewed
- Missing screenshots
- Link to required backend PR

2022-06-06 21:54 UTC, azanbinzahid requested changes

2022-06-06 21:54 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.jsx
> +  ];
Could this be refactored? Seems like a good use case of Array Map.

2022-06-06 21:54 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.jsx
> +                        modified: history.modified,
Please format dates, you may use `formatDate` from `utils`.

2022-06-06 21:54 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.jsx
> +              <Modal
Can this be moved from here for better readability?

2022-06-06 21:54 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.jsx
> +                      data={ssoRecord.history.map((history) => ({
or use a variable for data here instead.

2022-06-06 21:54 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.jsx
> +    history: PropTypes.arrayOf(PropTypes.object),
if we know all the fields in prior, we can add their types as well along with names.

2022-06-06 21:54 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.test.jsx
> +    });
Do we need this?

2022-06-10 07:13 UTC, DawoudSheraz commented on src/users/SingleSignOnRecordCard.jsx
> +  ];
+1

2022-06-10 07:13 UTC, DawoudSheraz commented on src/users/SingleSignOnRecordCard.jsx
> +                        modified: history.modified,
Yes, the dates are not human readable.

2022-06-10 07:14 UTC, DawoudSheraz commented on src/users/SingleSignOnRecordCard.jsx
> +              See History
nit: Instead of See History, either Change History or Edit History or even just History would do.

2022-06-10 07:17 UTC, DawoudSheraz commented on src/users/SingleSignOnRecordCard.test.jsx
> +          expect(text).toEqual(expires);
If needed, this can be broken down into separate unit tests.

2022-06-10 07:18 UTC, DawoudSheraz reviewed
nits/comments to address before final approval.

2022-06-13 12:58 UTC, Ali-D-Akbar commented on src/users/SingleSignOnRecordCard.test.jsx
> +    });
Need what?

2022-06-16 11:49 UTC, azanbinzahid reviewed
- a small refactor
- can you add more SS when there is data in extraData to ensure/verify consistency in design?

2022-06-16 11:49 UTC, azanbinzahid commented on src/users/SingleSignOnRecordCard.jsx
> +    [],
Let's reduce this code to take list of keys, use map and return list of obj in req format.

2022-06-16 11:51 UTC, DawoudSheraz approved these changes

2022-06-16 14:00 UTC, Ali-D-Akbar commented on src/users/SingleSignOnRecordCard.jsx
> +    [],
Done. Also, this is how the dict looks like. Also, the modal doesn't seem center aligned. We can get these done later in a followup PR.

<img width="1669" alt="Screenshot 2022-06-16 at 7 00 13 PM" src="https://user-images.githubusercontent.com/52413434/174086968-7d7ab1d0-1505-4238-85be-9aeac9996dbd.png">

2022-06-20 06:19 UTC, azanbinzahid approved these changes

2022-06-20 06:25 UTC, merged