feat: remove old UserPage, related older actions and version toggle
openedx-unsupported/frontend-app-support-tools pull request #245
Opened 2022-03-31 21:51 UTC by Ali-D-Akbar

2022-04-01 05:32 UTC, DawoudSheraz commented on src/users/v2/UserPage.jsx
> -import { LEARNER_INFO_TAB, TAB_PATH_MAP } from '../../SupportToolsTab/constants';
Why we are deleting v2 userpage?

2022-04-01 06:24 UTC, Ali-D-Akbar commented on src/users/v2/UserPage.jsx
> -import { LEARNER_INFO_TAB, TAB_PATH_MAP } from '../../SupportToolsTab/constants';
I moved v2/UserPage to actual directory.

2022-04-01 06:24 UTC, Ali-D-Akbar commented on src/users/v2/UserPage.jsx
> -import { LEARNER_INFO_TAB, TAB_PATH_MAP } from '../../SupportToolsTab/constants';
I moved v2/UserPage to actual directory.

2022-04-04 17:48 UTC, ansabgillani requested changes
Left a few comments. please look onto them.

2022-04-04 17:48 UTC, ansabgillani commented on src/users/data/test/onboardingStatus.js
>  const v2OnboardingStatusData = {
Rename this as onboardingStatusData and change the statuses

2022-04-04 17:48 UTC, ansabgillani commented on src/users/v2/OnboardingStatus.test.jsx
> +import v2OnboardingStatusData from '../data/test/onboardingStatus';
Why did we remove this alias?

2022-04-04 17:48 UTC, ansabgillani commented on src/users/v2/OnboardingStatus.test.jsx
> +    const onboardingData = { ...v2OnboardingStatusData, verifiedIn: nullData };
Can you update this v2OnboardingStatusData to onboardingStatusData? There is no sense in keeping it named as v2 if we're deprecating.

2022-04-04 17:50 UTC, Ali-D-Akbar commented on src/users/data/test/onboardingStatus.js
>  const v2OnboardingStatusData = {
will be done in the next PR.

2022-04-04 17:51 UTC, Ali-D-Akbar commented on src/users/v2/OnboardingStatus.test.jsx
> +import v2OnboardingStatusData from '../data/test/onboardingStatus';
bcz there is no need of it anymore. The `onboardingStatusData` has been removed from `../data/test/onboardingStatus`

2022-04-04 17:52 UTC, Ali-D-Akbar commented on src/users/v2/OnboardingStatus.test.jsx
> +    const onboardingData = { ...v2OnboardingStatusData, verifiedIn: nullData };
will be done in the next PR.

2022-04-04 17:52 UTC, ansabgillani approved these changes

2022-04-04 20:59 UTC, azanbinzahid approved these changes

2022-04-05 05:46 UTC, DawoudSheraz approved these changes

2022-04-05 08:00 UTC, merged