feat: add learner credentials
openedx-unsupported/frontend-app-support-tools pull request #253
Opened 2022-04-20 06:58 UTC by ansabgillani

2022-04-22 05:46 UTC, DawoudSheraz commented on src/users/data/api.js
> +          text: 'There was an error in retrieving credentials for the user',
nit: if we can use error.text or a similar attribute instead of a hard-coded error message, that will help the user know the real issue on UI instead of going to the network tab.

2022-04-22 05:47 UTC, DawoudSheraz commented on src/users/data/api.js
> +    return data;
since the API is paginated, are we not catering if more than one page is returned in the response?

2022-04-22 05:50 UTC, DawoudSheraz commented on src/users/LearnerCredentials.jsx
> +            columns={[
Where are the API call related errors rendered?

2022-04-22 05:57 UTC, DawoudSheraz reviewed
added some comments/questions.

2022-04-27 13:47 UTC, hurtstotouchfire commented on src/users/LearnerCredentials.jsx
> +            <p className="ml-4">No Credentials were Found.</p>
@oliviaruizknott I'm assuming all our bugs will just hit this line, but I'm wondering what happens in our certificate availability date cases. Possibly we could add more data here to help support identify that issue.

2022-04-27 13:53 UTC, hurtstotouchfire commented
Hey folks, I think any code review from Aperture here (Olivia and myself) can be considered non-blocking, and potentially we will follow up with our own PR. Thanks for building this! 🙏

2022-04-27 20:49 UTC, oliviaruizknott commented on src/users/LearnerCredentials.jsx
> +            <p className="ml-4">No Credentials were Found.</p>
Yes, in the future, I think we will want to add more data here; but this can be okay for now.

2022-04-27 21:00 UTC, oliviaruizknott requested changes
It is possible that I read too hastily and you are doing this filtering somewhere that I missed. In that case, forgive me! But:

It looks like your API call is retrieving _all_ `UserCredential`s for the user from the Credentials service.

The Credentials service keeps `UserCredential` records for **both course and program** credentials. That means you will get back mostly **course** credentials in your call (simply because there are more of them), which doesn’t seem to be the intent.

If the intent is to quickly show / link to **program** credentials / certificates, filter your call or the results by `type = 'program'`.

2022-04-27 21:00 UTC, oliviaruizknott commented on src/users/LearnerCredentials.jsx
> +                </Hyperlink>
If you don’t filter by `type = 'program'`, this will render lots of broken / bad links.

The Credentials service only _renders_ **program** credentials. Course certificates are rendered by edx-platform.

In other words, even though all these credential records will have a `credential.certificate_url`, only credentials where `type = "program"` will have valid / working urls. Where `type = "course-run"`, the `certificate_url` will 404.

2022-04-27 21:00 UTC, oliviaruizknott commented on src/users/LearnerCredentials.jsx
> +              programID: credential.credential.program_uuid,
Only credentials with `type = 'program'` will have this.

2022-04-27 21:00 UTC, oliviaruizknott commented on src/users/LearnerCredentials.jsx
> +  );
For what it’s worth, this might be overkill; the only attributes we have stored are:
```
                {
                    "name": "visible_date",
                    "value": < some date value >
                }
```

There are no other Attribute records other than `visible_date` in the whole database. You _could_ simplify this so that the table just has a `visible_date` column, rather than handling for any attribute.

But this works too!

2022-04-29 06:54 UTC, DawoudSheraz commented
Thank you for a detailed review and context @oliviaruizknott and @hurtstotouchfire. We will address the items that have been raised.

2022-05-12 04:22 UTC, ansabgillani commented
Apologies for the delayed response @oliviaruizknott and @hurtstotouchfire. Thank you for the detailed review. I will add the relevant checks and get back to you asap.

2022-05-18 18:40 UTC, DawoudSheraz reviewed
- to add a screenshot of credentials view in the PR description
- Small nits to address before final approval

2022-05-18 18:40 UTC, DawoudSheraz commented on src/users/data/api.js
> +          text: 'There was an error in retrieving credentials for the user',
@ansabgillani Still unresolved.

2022-05-18 18:40 UTC, DawoudSheraz commented on src/users/data/api.test.js
> +      expect(results[0]).toEqual(successResponse.results[0]);
verify the paginated results concat in a separate unit test.

2022-05-18 18:40 UTC, DawoudSheraz commented on src/users/LearnerCredentials.jsx
> +          setCredentials(response.results);
What happens if count is 0?

2022-05-20 06:28 UTC, ansabgillani commented on src/users/LearnerCredentials.jsx
> +              programID: credential.credential.program_uuid,
Resolved it out

2022-05-20 06:28 UTC, ansabgillani commented on src/users/LearnerCredentials.jsx
> +                </Hyperlink>
Resolved it out

2022-05-30 05:20 UTC, ansabgillani commented on src/users/data/api.test.js
> +      expect(results[0]).toEqual(successResponse.results[0]);
added.

2022-05-30 05:22 UTC, ansabgillani commented on src/users/LearnerCredentials.jsx
> +          setCredentials(response.results);
This means no credentials were present. So, the screen would display a 'No Credentials were found' error message

2022-05-30 05:25 UTC, ansabgillani commented on src/users/LearnerCredentials.jsx
> +            columns={[
Not addressing these errors for now because of this https://github.com/openedx/frontend-app-support-tools/pull/253/files#r860233589

2022-05-30 07:37 UTC, DawoudSheraz commented on src/users/LearnerCredentials.jsx
> +          setCredentials(response.results);
What happens if there is an error when fetching credentials? Where will the user see them?

2022-05-30 07:39 UTC, DawoudSheraz commented on src/users/LearnerCredentials.jsx
> +          setCredentials(response.results);
The above API call is only handling the cases when there is no error in the API call.

2022-05-30 07:42 UTC, DawoudSheraz reviewed
1-2 questions added.

2022-05-30 21:29 UTC, Ali-D-Akbar reviewed
Honestly, I think we should use the sub-table approach we used in enrollment/entitlement. The current approach really messes up the credential table.

<img width="1388" alt="Screenshot 2022-05-31 at 2 10 57 AM" src="https://user-images.githubusercontent.com/52413434/171060823-3c57cd15-6b71-4b55-8e52-9fd9e5a21a7c.png">

2022-05-30 21:29 UTC, Ali-D-Akbar commented on src/users/data/api.js
> +          text: error.text ? error.text : 'There was an error in retrieving credentials for the user',
nit: error retrieving

2022-05-31 12:21 UTC, justinhynes commented on src/users/LearnerCredentials.jsx
> +              Hide
Since this is in the `openedx` org, which makes me believe this is used outside of edX/2U, does the Support Tools MFE support localization? Should `Hide` be hard-coded English?

2022-05-31 12:21 UTC, justinhynes commented on src/users/LearnerCredentials.jsx
> +            Show
See above comment on localization of `Hide`. Should `Show` be hard-coded English?

2022-05-31 12:23 UTC, justinhynes commented on src/users/LearnerCredentials.jsx
> +            <p className="ml-4">No Credentials were Found.</p>
Same question here (see above comment); Should `No Credentials were Found` be hard-coded English?

2022-05-31 12:25 UTC, justinhynes commented on src/users/LearnerCredentials.jsx
> +        <h3>Learner Credentials</h3>
Nit: Same question here, should `Learner Credentials` be hard-coded English?

2022-05-31 17:38 UTC, oliviaruizknott approved these changes
I re-reviewed for the handling of _program_ certificates only and am satisfied by the filtering in the API call! Thanks.

(Though I’m trusting that you checked that this actually works; I haven’t checked the Credentials side.)

2022-06-10 07:34 UTC, DawoudSheraz approved these changes
Looks good codewise. One improvement for a follow-up PR:
- Use table component expandedrow behavior to display additional attributes

2022-06-16 14:34 UTC, merged