feat: learner record tab
openedx-unsupported/frontend-app-support-tools pull request #273
Opened 2022-09-28 17:09 UTC by MaxFrank13

This PR adds a new "Learner Records" tab under the Learner Information tab. This new tab contains information about a Learner's program records. 

![Screen Shot 2022-09-28 at 12 52 51 PM](https://user-images.githubusercontent.com/92897870/192842729-dec727ec-3384-42a3-bf9f-0e74394f42f0.png)

This feature is intended to replace masquerading for the [current Learner Records page](https://credentials.edx.org/records/).  Once we convert this page to an MFE, it will no longer support masquerading and this tab will be provided as a way for the support team to look up a Learner's records.

![Screen Shot 2022-09-28 at 12 54 33 PM](https://user-images.githubusercontent.com/92897870/192843058-7bd30ba2-f1e1-4a44-8b20-b0e5a2f3f637.png)

NOTE: This feature _does not_ allow for the creation of public links. The option to copy a link will only appear if a public record exists for that learner (captured in the `shared_program_record_uuid` field of the initial API response). 

There is a `USE_LEARNER_RECORD_TAB` WaffleFlag that has been added to give the option of turning off the tab completely. As well as a `RECORDS_BASE_URL` variable that is used by the copy button when building a public link.

2022-09-28 17:30 UTC, justinhynes commented on .env.development
> +RECORDS_BASE_URL='localhost:1990'
Do we need defaults for these settings in the `.env` file as well?

2022-09-28 17:35 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +      <h3>Learner Records</h3>
I was under the impression that we should always be starting from an `H1` and moving down. I see that this is contained within a "`section`" component, so maybe there is already an H1 in the hierachy? Should this be "styled like" an H3 using CSS rather than using the `H3` tag?

Maybe a11y isn't as important as this is an internal support tool?

(Honestly just asking because I am trying to flex some "rules" I _think_ I understand, but it's an honest question for my own edification)

2022-09-28 17:36 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +                  <p>{record.program.school} | {record.platform_name}</p>
Do we _need_ the `school` and `platform_name` here? It makes sense on the Program Record page, but I'm not sure it's useful here. I could see having the program type and program name.

2022-09-28 17:37 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +                    Copy public record link
Should this be hard-coded english? This tool exists as part of the `openedx` GitHub org and it _could_ be used by other Open edX operators. 

My assumption here is that we'd want to resource the string.

2022-09-28 17:38 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +                  <p>Last updated: {new Date(record.program.last_updated).toLocaleDateString()}</p>
See below comment on having hard-coded english here.

2022-09-28 17:38 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +                      : 'Not Earned',
See above comment on hard-coded english.

2022-09-28 17:39 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +                    Header: 'Course Name',
For each `Header` in this section from lines 55 - 83, should these be resourced as well?

2022-09-28 17:40 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +              <p>No results found for username: {username}</p>
Same hardcoded-english observation/question here.

2022-09-28 17:43 UTC, MaxFrank13 commented on src/users/LearnerRecords.jsx
> +                    Copy public record link
I had thought so as well but when I initially looked over the other components I saw all hard-coded english. It looks like they are resourcing in some parts with the `FormattedMessage` component. Given that the component is available, it should be easy enough to modify at least the strings I've added here. I'll get on those changes 👍

2022-09-28 17:56 UTC, Tj-Tracy approved these changes
LGTM 👍

2022-09-28 17:56 UTC, Tj-Tracy commented on src/users/data/test/records.js
> +const records = [
Not worthwhile to change now, but in the future, we tend to use Rosie for this kind of test data: https://github.com/rosiejs/rosie

Just something to keep in mind for the next time you're doing something like this

2022-09-28 18:07 UTC, justinhynes commented
@MaxFrank13  -- Are we missing the status of the Program Certificate in the table?

2022-09-28 18:07 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +                    Copy public record link
Thank you!!

2022-09-28 18:09 UTC, justinhynes requested changes
I think we'd want to display the overall status of the Program certificate as well in the tables.

2022-09-28 18:12 UTC, MaxFrank13 commented on src/users/LearnerRecords.jsx
> +      <h3>Learner Records</h3>
It's my understanding that `h1` is used for the most important title on the _entire_ page. I don't believe there actually is one for this page. The "Support Tools" string at the top is an `h2`. All of the other headers for the tabs were `h3` so that's why I settled on it. I think it makes sense as an `h3` given that is a subsection of the page. However, I'm not well-versed on a11y

2022-09-28 18:20 UTC, MaxFrank13 commented on src/users/LearnerRecords.jsx
> +                  <p>{record.program.school} | {record.platform_name}</p>
Going to replace this line with the "Status" of the record

2022-09-28 19:31 UTC, justinhynes commented on src/users/LearnerRecords.jsx
> +      <h3>Learner Records</h3>
If this were a learner/partner facing page, I'd be inclined to chase down this answer. For now, I think this is sufficient. Thanks, Max.

2022-09-28 19:32 UTC, MaxFrank13 commented
> I think we'd want to display the overall status of the Program certificate as well in the tables.

Added 👍 

https://github.com/openedx/frontend-app-support-tools/pull/273#pullrequestreview-1124152820

2022-09-28 19:34 UTC, justinhynes approved these changes
Thanks for all the quick changes! 👍

2022-10-05 06:58 UTC, DawoudSheraz commented on src/users/LearnerRecords.jsx
> +      intl.formatMessage(messages.partiallyCompletedStatus)
nitt: you can use JSON here, with status as keys and expected message as value to remove if conditions.

2022-10-05 07:00 UTC, DawoudSheraz commented on src/users/data/test/records.js
> +const records = [
Oh, this is great. Factory-boy for JS tests it seems.

2022-10-05 07:03 UTC, DawoudSheraz commented on src/users/data/api.js
> +
What should be the behavior here if one of the program record calls is not successful and there is an error message returned?

2022-10-05 07:05 UTC, DawoudSheraz commented on src/users/LearnerRecords.test.jsx
> +    wrapper.unmount();
nit: the unmount can be moved to afterEach.

2022-10-05 07:07 UTC, DawoudSheraz reviewed
Overall, the changes are good. Can you add testing steps, including some pointers on setting test data in credentials, so that I can test it out on local, please? Thank you

2022-10-05 19:16 UTC, MaxFrank13 commented on src/users/data/api.js
> +
This error would be caught by the `catch` below it. That error message is then displayed as an alert in the UI. I will add a test that demonstrates what happens when one of the calls in the `Promise.all()` fails 👍

2022-10-05 19:57 UTC, MaxFrank13 commented
> Overall, the changes are good. Can you add testing steps, including some pointers on setting test data in credentials, so that I can test it out on local, please? Thank you

In order to test the new tab UI, you'll need:

- A user who is enrolled in at least one course in a program and earned a certificate for that program. This is necessary for the REST API to return any data. I used myself (username=edx) when testing this locally.

  - Make sure you have pulled the latest version of Credentials to have access to this REST API

- Add new environment variables. Create and set a `USE_LEARNER_RECORD_TAB` variable to `true` and then `RECORDS_BASE_URL` to `localhost:1990`

From there, you should be able to see a list of the user's earned records under the Learner Records tab. 

- If a public version of the record exists, there will be a button for copying a link to that record. Click the "Copy public record link" and make sure a link copies to your clipboard. Note that in order for this link to work, you'll need to have the latest version Learner Record MFE running.

  - If you want to create a public record, go to the Learner Record page (Learner Record MFE), click on "View Program Record" for an enrolled program, and  select "Create public record link"
  - Refreshing the support tool should render a button for copying the link
  
-  The REST API can also be tested to verify that the data is coming through at: 

   - `http://localhost:18150/records/api/v1/program_records/{program_id}/?username={username}`
   - NOTE: the REST API has been deployed to Production

2022-10-05 20:12 UTC, MaxFrank13 commented on src/users/LearnerRecords.jsx
> +      intl.formatMessage(messages.partiallyCompletedStatus)
Could you elaborate further on this? I think I understand but am having trouble piecing it together. The `program.completed` and `program.empty` fields are both booleans. My thinking is to convert these into JSON keys who's values correspond to their appropriate message, but how are you suggesting to do this?

2022-10-06 05:12 UTC, ansabgillani commented on src/users/LearnerRecords.test.jsx
> +    wrapper.unmount();
Refactor still needs to be addressed.

2022-10-06 05:13 UTC, ansabgillani commented on src/users/data/api.js
> +      await Promise.all(data.enrolled_programs.map(program => getAuthenticatedHttpClient().get(`${AppUrls.getLearnerRecordsUrl()}/${program.uuid}/?username=${username}`)
nit: Can we maybe try to make it indented for better readability?

2022-10-06 05:14 UTC, ansabgillani commented
The changes look good to me. A couple of refactors that may improve the code readability, otherwise good to go.

2022-10-06 05:15 UTC, ansabgillani approved these changes

2022-10-06 05:49 UTC, DawoudSheraz commented on src/users/LearnerRecords.jsx
> +      intl.formatMessage(messages.partiallyCompletedStatus)
Oh, ok. I mistook them for strings.

2022-10-06 15:46 UTC, merged