feat: CatalogQuery Api integration and context
openedx-unsupported/frontend-app-support-tools pull request #310
Opened 2023-03-13 17:27 UTC by brobro10000

Adds API data in context to populate on conditional rendering
Populate dropdown and json text area with catalog query api data.
Adds alerting for bad api response

Tests WIP

2023-03-22 22:46 UTC, marlonkeating requested changes

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/CustomCatalog/ProvisioningFormCustomCatalogDropdown.jsx
> +          catalogQuery: catalogQueries.data.filter(({ uuid }) => uuid === value.split(' - ')[1].trim())[0],
nit: A couple micro-optimizations
```suggestion
    if (value) {
      const valueUuid = value.split(' - ')[1].trim();
      setCatalogQueryCategory({
        catalogQueryMetadata: {
          catalogQuery: catalogQueries.data.find(({ uuid }) => uuid === valueUuid),
```

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/CustomCatalog/ProvisioningFormCustomCatalogTextArea.jsx
> +  // const sampleCourseModesResponse = [
Remove

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/CustomCatalog/ProvisioningFormCustomCatalogTextArea.jsx
> +      {/* <Form.Control
Remove

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/CustomCatalog/ProvisioningFormCustomCatalogTitle.jsx
> +          value={catalogQueryTitle || null}
Is it important to have it be null rather than undefined?
```suggestion
          value={catalogQueryTitle}
```

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/CustomCatalog/ProvisioningFormCustomCatalog.jsx
> +};
I notice this index is used in a lot of propTypes.  Is it worth it breaking it out into a separate reusable propTypes object?

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/data/constants.js
> +    return `/admin/enterprise/enterprisecustomercatalog/?q=${enterpriseCustomerUUID.slice(0, 7)}`;
This url generation looks like it would be better as a helper method, considering the embedded logic for using just the first 7 characters of the enterprise customer's uuid.

2023-03-22 22:46 UTC, marlonkeating commented on src/Configuration/Provisioning/data/utils.js
> +}
nit: The javascript sort function only counts positive and negative numbers (besides zero), they don't have to be +/- 1.
```suggestion
export function sortedCatalogQueries(catalogQueries) {
  return catalogQueries.sort((b, a) => a - b);
}
```

2023-03-24 14:08 UTC, brobro10000 commented on src/Configuration/Provisioning/data/utils.js
> +}
Hey Marlon, I tried refactoring the code, but it would not sort the dates in  the correct order. Doing a greater than less then on the value and sorting that way seems to be working correctly though and is passing test / live sanity check

2023-03-24 18:08 UTC, marlonkeating requested changes

2023-03-24 18:08 UTC, marlonkeating commented on src/Configuration/Provisioning/data/utils.js
> +export const lmsCustomerCatalog = {
Some comments would be helpful for this code

2023-03-24 18:08 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/PolicyForm/ProvisioningFormSourceCustomCatalogHeader.jsx
> +          destination={`${LMS_BASE_URL}${lmsCustomerCatalog.queryBy(formData?.enterpriseUUID || null)}`}
Is it important that null be passed rather than undefined?
```suggestion
          destination={`${LMS_BASE_URL}${lmsCustomerCatalog.queryBy(formData?.enterpriseUUID)}`}
```

2023-03-24 18:08 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/CustomCatalog/tests/ProvisioningFormCustomCatalogDropdown.test.jsx
> +  });
Anything happening here?

2023-03-24 18:21 UTC, marlonkeating approved these changes

2023-04-04 20:28 UTC, merged