feat: add order history table
openedx-unsupported/frontend-app-support-tools pull request #339
Opened 2023-06-06 09:26 UTC by Ali-D-Akbar

[PROD-3163](https://2u-internal.atlassian.net/browse/PROD-3163)

2023-06-09 05:30 UTC, DawoudSheraz commented on src/users/orderHistory/OrderHistory.jsx
> +    isAllRowsExpanded: PropTypes.bool.isRequired,
Do we really need expander here? Can't it all be displayed on a single row?

2023-06-09 05:40 UTC, Ali-D-Akbar commented on src/users/orderHistory/OrderHistory.jsx
> +    isAllRowsExpanded: PropTypes.bool.isRequired,
Each order have multiple lines having the products so it is another list.

2023-06-09 11:17 UTC, AfaqShuaib09 commented on src/users/orderHistory/OrderHistory.jsx
> +      },
Can we use loop over here for `Header`, `accessor` and `sortable` value instead of hardcoding them?

2023-06-09 11:17 UTC, AfaqShuaib09 commented on src/users/orderHistory/OrderHistory.jsx
> +    ],
same here

2023-06-12 06:43 UTC, zawan-ila requested changes
Tests are missing.

2023-06-12 06:43 UTC, zawan-ila commented on package-lock.json
> -      "dev": true,
[thinking] What are these changes for? They don't look like version upgrades.

2023-06-12 06:43 UTC, zawan-ila commented on src/users/EntitlementsAndEnrollmentsContainer.jsx
> +      <OrderHistory
Should we change the name of the file now?

2023-06-12 06:43 UTC, zawan-ila commented on src/users/orderHistory/OrderHistory.jsx
> +import { faMinus, faPlus } from '@fortawesome/free-solid-svg-icons';
Nice to use paragon icons here?

2023-06-12 06:43 UTC, zawan-ila commented on src/users/data/api.js
> +    return [];
Would be nice to do something with this error here. Or at least return something like `null`?

2023-06-13 07:36 UTC, Ali-D-Akbar commented on src/users/EntitlementsAndEnrollmentsContainer.jsx
> +      <OrderHistory
Order History seems to have related to enrollments and entitlements but please feel free to suggest a better name.

2023-06-13 07:55 UTC, Ali-D-Akbar commented on src/users/data/api.js
> +    return [];
Order api doesn't have any explicit errors. I went with with empty list to show nothing on the order history even if an error occurs.

2023-06-14 05:46 UTC, Ali-D-Akbar commented on src/users/orderHistory/OrderHistory.jsx
> +import { faMinus, faPlus } from '@fortawesome/free-solid-svg-icons';
Not sure what was the reason back then but we couldn't use the paragon ones before.

2023-06-14 05:47 UTC, Ali-D-Akbar commented on package-lock.json
> -      "dev": true,
Kinda needed for the CI Tests to pass

2023-06-14 05:48 UTC, Ali-D-Akbar commented on src/users/orderHistory/OrderHistory.jsx
> +      },
It won't reduce the code by much. We'll still be making arrays for Headers, accessors, sortable, id and Cell keys.

2023-06-14 11:58 UTC, zawan-ila approved these changes

2023-06-15 18:52 UTC, AfaqShuaib09 approved these changes

2023-06-16 05:25 UTC, DawoudSheraz commented on src/users/EntitlementsAndEnrollmentsContainer.jsx
> +      <OrderHistory
Let's move this to a new tab, Learner Purchases. Enrollment & entitlements tab is already very bulky.

2023-06-16 05:27 UTC, DawoudSheraz commented on src/users/data/api.js
> +    return [];
But we can add explicit messages based on error or response status.

2023-06-16 05:28 UTC, DawoudSheraz commented on src/users/orderHistory/OrderHistory.jsx
> +import { faMinus, faPlus } from '@fortawesome/free-solid-svg-icons';
We can use paragon icons, the version is latest or near to latest.

2023-06-16 05:36 UTC, DawoudSheraz approved these changes
a few nits to address before merge

2023-06-20 21:11 UTC, merged