Implements Detailed Plan View with Edit Mode Button
openedx-unsupported/frontend-app-support-tools pull request #352
Opened 2023-08-24 00:36 UTC by katrinan029

2023-08-25 19:32 UTC, marlonkeating requested changes

2023-08-25 19:32 UTC, marlonkeating commented on src/Configuration/Provisioning/SubsidyDetailView/PolicyDetailView/CustomCatalogDetail.jsx
> +  return catalogTitle;
nit: Can reduce code duplication
```suggestion
  let separator = ' - ';
  if (catalogTitle.includes(separator)) {
    return catalogTitle.split(separator)[1];
  }
  return catalogTitle;
```

2023-08-25 19:32 UTC, marlonkeating commented on src/Configuration/Provisioning/SubsidyDetailView/PolicyDetailView/AssociatedCatalogDetail.jsx
> +        {(catalogType === 'Custom') && <CustomCatalogDetail catalogTitle={associatedCatalog} />}
```suggestion
        {(catalogType === CATALOG.OPTIONS.custom) && <CustomCatalogDetail catalogTitle={associatedCatalog} />}
```

2023-08-25 19:32 UTC, marlonkeating commented on src/Configuration/Provisioning/SubsidyDetailView/SubsidyDetailView.jsx
> +            return Object.assign({}, ...catalog.data.results);
Don't think we need Object.assign here?
```suggestion
            return {...catalog.data.results};
```

2023-08-28 17:28 UTC, katrinan029 commented on src/Configuration/Provisioning/SubsidyDetailView/PolicyDetailView/CustomCatalogDetail.jsx
> +  return catalogTitle;
good call!

2023-08-28 17:30 UTC, katrinan029 commented on src/Configuration/Provisioning/SubsidyDetailView/SubsidyDetailView.jsx
> +            return Object.assign({}, ...catalog.data.results);
The reason I am using the `Object.assign` here is to remove the index. See differences below. 
![Screenshot 2023-08-28 at 10 27 43 AM](https://github.com/openedx/frontend-app-support-tools/assets/71999631/901b9bca-9501-4769-a705-a286592dc3ba)

2023-08-28 18:29 UTC, marlonkeating approved these changes

2023-08-28 19:09 UTC, merged