feat: implements edit feature
openedx-unsupported/frontend-app-support-tools pull request #354
Opened 2023-09-01 22:43 UTC by katrinan029

2023-09-06 14:48 UTC, marlonkeating requested changes

2023-09-06 14:48 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/PolicyForm/ProvisioningFormAccountDetails.jsx
> +      {isEditMode ? (
Should the logic be reversed here?  It looks to be rendering the static view when `isEditMode === true`.

2023-09-06 14:48 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/ProvisioningFormTitle.jsx
> +    setValue(e.target.value);
nit: Can clean up a couple things here
```suggestion
    setValue(newEventValue);
    if (newEventValue === '') {
      setInvalidSubsidyFields({ ...subsidy, subsidyTitle: false });
      setSubsidyTitle('');
      return;
    }
```

2023-09-06 14:48 UTC, marlonkeating commented on src/Configuration/Provisioning/data/hooks.js
> +        customerName: customer.data[0]?.name,
nit: `subsidyResponse.data.results[0]` and `customer.data[0]` get used a lot in the following code, might improve readability to put them in variable.

2023-09-06 14:48 UTC, marlonkeating commented on src/Configuration/Provisioning/data/hooks.js
Looks like this file could use more test coverage.

2023-09-06 22:10 UTC, katrinan029 commented on src/Configuration/Provisioning/ProvisioningForm/PolicyForm/ProvisioningFormAccountDetails.jsx
> +      {isEditMode ? (
Based on the figma design, we don't want the user to edit the budget's total balance so this should be static. 

![Screenshot 2023-09-06 at 3 09 42 PM](https://github.com/openedx/frontend-app-support-tools/assets/71999631/dd9e40fa-9d9d-4bcc-8b6a-edfd16f3bfdd)

2023-09-06 22:53 UTC, marlonkeating commented on src/Configuration/Provisioning/ProvisioningForm/PolicyForm/ProvisioningFormAccountDetails.jsx
> +      {isEditMode ? (
But if `isEditMode` is false, it renders what looks to be an editable form field

2023-09-07 05:32 UTC, katrinan029 commented on src/Configuration/Provisioning/ProvisioningForm/PolicyForm/ProvisioningFormAccountDetails.jsx
> +      {isEditMode ? (
Yup! That's correct, if `isEditMode` is false, the form field is editable because the form is a new form. We can huddle about this if needed.

2023-09-12 16:16 UTC, marlonkeating approved these changes

2023-09-12 16:16 UTC, marlonkeating commented on src/Configuration/Provisioning/data/hooks.js
> +    const subsidyCustomerId = subsidyResponse.data.results[0].enterprise_customer_uuid;
nit
```suggestion
    const subsidyData = subsidyResponse.data.results[0];
    const subsidyCustomerId = subsidyData.enterprise_customer_uuid;
```

2023-09-12 17:10 UTC, merged