Add Budget Distribution Selection in View and Edit modes
openedx-unsupported/frontend-app-support-tools pull request #371
Opened 2023-12-10 23:06 UTC by kiram15

[Figma
](https://www.figma.com/file/8da9TyEpEzgxQld3DZE67w/LC2---Top-down-Assignment?node-id=3536%3A45400&mode=dev) | [Jira Ticket ](https://2u-internal.atlassian.net/browse/ENT-7959)
<img width="1002" alt="Screenshot 2023-12-10 at 3 27 11 PM" src="https://github.com/openedx/frontend-app-support-tools/assets/31229189/8d5c3ae0-7d89-4a8e-8771-da011f169aff">
<img width="982" alt="Screenshot 2023-12-10 at 3 26 34 PM" src="https://github.com/openedx/frontend-app-support-tools/assets/31229189/0544cc1d-8f60-4e3c-bd73-2405b6d35ce9">

2023-12-11 17:03 UTC, marlonkeating approved these changes

2023-12-11 17:03 UTC, marlonkeating commented on src/Configuration/Provisioning/SubsidyDetailView/PolicyDetailView/PolicyDistributionDetail.jsx
> +            && POLICY_TYPE.OPTIONS.LEARNER_SELECTS.DESCRIPTION}
nit: can shorten
```suggestion
          {POLICY_TYPE.OPTIONS[policyType]?.DESCRIPTION}
```

2023-12-11 22:28 UTC, katrinan029 requested changes
Code looks good! The edit mode UI in view mode just needs to be updated to match figma.

![Screenshot 2023-12-11 at 2 26 54 PM](https://github.com/openedx/frontend-app-support-tools/assets/71999631/ba0eb49f-31c0-4dee-a998-69322b1290ed)

2023-12-12 23:19 UTC, katrinan029 approved these changes
🚢

2023-12-12 23:19 UTC, merged