feat: update learner credit plan cards to use subsidies
openedx-unsupported/frontend-app-support-tools pull request #419
Opened 2024-09-13 22:02 UTC by katrinan029

2024-09-24 22:16 UTC, marlonkeating commented on .env.development
> +LICENSE_MANAGER_DJANGO_URL='http://localhost:18170'
Is there a need for a new `LICENSE_MANAGER_DJANGO_URL` variable if the value is the same as the existing `LICENSE_MANAGER_URL`?

2024-09-25 14:22 UTC, marlonkeating requested changes

2024-09-25 14:22 UTC, marlonkeating commented on src/data/services/utils.js
> +    return fetchPaginatedData(responseData.next, resultsCopy);
Looks like we could use some test coverage in the pagination case.

2024-09-25 14:22 UTC, marlonkeating commented on src/Configuration/Customers/data/utils.js
> +    logError(error);
Looks like we could use some test coverage in the error case.

2024-09-25 15:13 UTC, katrinan029 commented on .env.development
> +LICENSE_MANAGER_DJANGO_URL='http://localhost:18170'
yes, the `LICENSE_MANAGER_URL` variable is use for fetching subscriptions data and the `LICENSE_MANAGER_DJANGO_URL` is used as the django admin url. we ran into an issue with fetching the data when we used the same url. the fetching one should be `license-manager.edx.org` and the admin django screen is `license-manager-internal.edx.org`.

2024-09-25 15:59 UTC, marlonkeating approved these changes

2024-09-25 20:46 UTC, merged